[alembic]
script_location = ./alembic
sqlalchemy.url = sqlite:///./quantive.db

[loggers]
keys = root,sqlalchemy.engine,sqlalchemy.dialects,alembic

[handlers]
keys = console

[formatters]
keys = generic

[formatter_generic]
format = %(asctime)s %(levelname)s %(name)s %(message)s

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine
propagate = 0

[logger_sqlalchemy.dialects]
level = WARN
handlers =
qualname = sqlalchemy.dialects
propagate = 0

[logger_alembic]
level = INFO
handlers =
qualname = alembic
