"""Versioned tax-knowledge packs by (jurisdiction, tax year).

Honesty contract (enforced by tests):
- Every rule summary must tell the user to VERIFY against the cited authority.
- Sources name the authority + what to check, never a fabricated section number.
- No dollar savings, no eligibility guarantees — relevance + requirements only.
- Unknown/unsupported countries fall back to GEN (generic) rules only.

Jurisdiction codes: MX, US, BD, GEN (generic fallback).
"""
from __future__ import annotations

VERIFY_IRS = "IRS publications for the current tax year — verify before acting"
VERIFY_NBR = "NBR / Finance Act for the current assessment year — verify before acting"
VERIFY_SAT = "SAT / miscelánea fiscal vigente — verificar antes de actuar"
VERIFY_GEN = "Current rules of your jurisdiction — verify with a qualified professional"


def _rule(rid, juris, year, topic, title, summary, requirements, docs, sources):
    return {
        "id": rid, "jurisdiction": juris, "tax_year": year, "topic": topic,
        "title": title, "summary": summary, "requirements": requirements,
        "docs_required": docs, "limits": {},
        "sources": sources if isinstance(sources, list) else [sources],
        "effective_from": f"{year}-01-01", "effective_to": f"{year}-12-31",
    }


GEN_2026 = [
    _rule("GEN-2026-medical-expenses", "GEN", 2026, "health",
          "Medical expenses — potentially relevant",
          "Medical expenses are often jurisdiction-limited. Documentation required. Verify thresholds and eligible categories.",
          ["qualifying expenses", "receipts"], ["receipts", "insurance statements"], VERIFY_GEN),
    _rule("GEN-2026-retirement", "GEN", 2026, "retirement",
          "Retirement contributions — potentially relevant",
          "Retirement contributions may have limits or incentives depending on jurisdiction and account type. Verify.",
          ["eligible account"], ["contribution statements"], VERIFY_GEN),
    _rule("GEN-2026-education", "GEN", 2026, "education",
          "Education expenses — potentially relevant",
          "Education treatment varies widely by jurisdiction. Low default relevance until confirmed. Verify.",
          ["eligible expenses"], ["tuition receipts"], VERIFY_GEN),
    _rule("GEN-2026-home-office", "GEN", 2026, "work",
          "Home office — needs verification",
          "Home-office treatment depends on regime, exclusivity, and activity. High verification burden. Verify.",
          ["exclusive use evidence", "applicable regime"], ["expense records"], VERIFY_GEN),
    _rule("GEN-2026-housing-interest", "GEN", 2026, "housing",
          "Housing loan interest — potentially relevant",
          "Housing loan interest may be relevant depending on loan type, regime, and documentation. Verify.",
          ["qualifying loan", "applicable tax regime"], ["annual loan statement"], VERIFY_GEN),
    _rule("GEN-2026-donations", "GEN", 2026, "donations",
          "Charitable donations — potentially relevant",
          "Donation treatment (deduction vs credit, eligible recipients, receipt thresholds) varies by jurisdiction. Verify.",
          ["eligible recipient", "proof of donation"], ["donation receipts"], VERIFY_GEN),
]

MX_2026 = [
    _rule("MX-2026-mortgage-interest", "MX", 2026, "housing",
          "Mortgage interest — potentially relevant",
          "Mortgage interest may be relevant depending on regime and documentation. Requires verification. " + VERIFY_SAT,
          ["qualifying mortgage", "applicable tax regime"], ["annual mortgage statement (constancia anual)"],
          VERIFY_SAT),
]

US_2026 = [
    # ── Deductions (Schedule A / Above-the-Line) ──────────────────────
    _rule("US-2026-mortgage-interest", "US", 2026, "housing",
          "Mortgage interest (IRC §163) — potentially relevant",
          "May be deductible if you itemize; compare against the standard deduction. Acquisition-debt limits apply. " + VERIFY_IRS,
          ["itemize deductions", "qualifying acquisition debt"], ["Form 1098", "loan statements"], VERIFY_IRS),
    _rule("US-2026-salt", "US", 2026, "housing",
          "State and local taxes (IRC §164, $10K cap) — check current cap",
          "SALT deductibility has a $10,000 cap ($5,000 MFS). Itemizers only. Confirm current-year cap before assuming. " + VERIFY_IRS,
          ["itemize deductions"], ["property tax bills", "state income tax records"], VERIFY_IRS),
    _rule("US-2026-charitable", "US", 2026, "donations",
          "Charitable contributions (IRC §170) — potentially relevant",
          "Generally for itemizers, with AGI-percentage limits (60% cash, 30% appreciated property). Verify current limits. " + VERIFY_IRS,
          ["itemize deductions", "eligible organization"], ["receipts", "acknowledgment letters"], VERIFY_IRS),
    _rule("US-2026-charitable-bunching", "US", 2026, "donations",
          "Charitable contribution bunching — strategic opportunity",
          "Bunching two years of donations into one year may push you above the standard deduction threshold. Consider a donor-advised fund. " + VERIFY_IRS,
          ["itemize deductions", "eligible organization"], ["receipts", "DAF statements"], VERIFY_IRS),
    _rule("US-2026-medical-75pct", "US", 2026, "health",
          "Medical expenses (IRC §213, 7.5% AGI floor) — potentially relevant",
          "Only unreimbursed expenses exceeding 7.5% of AGI count, and only if you itemize. Verify the current floor. " + VERIFY_IRS,
          ["itemize deductions", "expenses above AGI floor"], ["receipts", "insurance statements"], VERIFY_IRS),
    _rule("US-2026-student-loan-interest", "US", 2026, "education",
          "Student loan interest (IRC §221) — potentially relevant",
          "Up to $2,500/year with income phaseouts; above-the-line deduction. Verify current phaseout ranges. " + VERIFY_IRS,
          ["eligible loan", "income within phaseout range"], ["Form 1098-E"], VERIFY_IRS),
    _rule("US-2026-home-office", "US", 2026, "work",
          "Home office (IRC §168(f)(1)) — needs verification",
          "Exclusive-and-regular-use test; simplified ($5/sqft, max $1,500) vs actual-expense method. Self-employed only. " + VERIFY_IRS,
          ["exclusive use evidence", "self-employment income"], ["expense records", "floor plan"], VERIFY_IRS),
    _rule("US-2026-hsa", "US", 2026, "health",
          "Health Savings Account (IRC §223) — potentially relevant",
          "Triple tax advantage: deductible contributions, tax-free growth, tax-free qualified withdrawals. 2026 limits apply. " + VERIFY_IRS,
          ["high-deductible health plan", "no other coverage"], ["Form 5498-SA", "Form 1099-SA"], VERIFY_IRS),
    _rule("US-2026-fsa", "US", 2026, "health",
          "Flexible Spending Account (IRC §125) — potentially relevant",
          "Pre-tax contributions for medical or dependent care expenses. Use-it-or-lose-it rules apply. " + VERIFY_IRS,
          ["employer FSA plan"], ["FSA election statements"], VERIFY_IRS),
    _rule("US-2026-dependent-care-fsa", "US", 2026, "family",
          "Dependent Care FSA (IRC §129) — potentially relevant",
          "Up to $5,000/year pre-tax for child/dependent care while you work. Coordinate with child care credit. " + VERIFY_IRS,
          ["qualifying dependent", "work-related care"], ["care provider receipts", "EIN/SSN"], VERIFY_IRS),

    # ── Retirement ────────────────────────────────────────────────────
    _rule("US-2026-401k", "US", 2026, "retirement",
          "401(k) contributions (IRC §402(g)) — potentially relevant",
          "Employee elective deferrals up to $23,500 (2026); catch-up for 50+. Employer match is additional. " + VERIFY_IRS,
          ["employer 401(k) plan"], ["W-2 Box 12"], VERIFY_IRS),
    _rule("US-2026-traditional-ira", "US", 2026, "retirement",
          "Traditional IRA deduction (IRC §219) — potentially relevant",
          "Deductible if not covered by workplace plan, or if below income phaseout. Verify current limits. " + VERIFY_IRS,
          ["eligible IRA", "income within limits"], ["Form 5498", "contribution receipts"], VERIFY_IRS),
    _rule("US-2026-roth-ira", "US", 2026, "retirement",
          "Roth IRA contributions (IRC §408A) — strategic opportunity",
          "Not deductible, but tax-free growth and withdrawals. Income phaseouts apply. Backdoor Roth may be available. " + VERIFY_IRS,
          ["income within phaseout"], ["Form 5498"], VERIFY_IRS),
    _rule("US-2026-roth-conversion", "US", 2026, "retirement",
          "Roth conversion ladder — strategic opportunity",
          "Convert Traditional IRA/401(k) to Roth in low-income years. Pay tax now for tax-free withdrawals later. Multi-year strategy. " + VERIFY_IRS,
          ["Traditional IRA or 401(k) balance", "low-income year"], ["conversion records"], VERIFY_IRS),
    _rule("US-2026-sep-ira", "US", 2026, "retirement",
          "SEP-IRA contributions (IRC §408(k)) — potentially relevant",
          "Self-employed can contribute up to 25% of net self-employment income, up to annual cap. " + VERIFY_IRS,
          ["self-employment income"], ["SEP-IRA contribution records"], VERIFY_IRS),
    _rule("US-2026-ira-catchup", "US", 2026, "retirement",
          "IRA/401(k) catch-up contributions (IRC §219(b)) — potentially relevant",
          "Age 50+ catch-up contributions: additional $7,500 for 401(k), $1,000 for IRA. Verify current amounts. " + VERIFY_IRS,
          ["age 50 or older"], ["contribution records"], VERIFY_IRS),
    _rule("US-2026-education-credit-saver", "US", 2026, "retirement",
          "Retirement Savings Contribution Credit (IRC §25B) — potentially relevant",
          "Credit for retirement contributions if AGI below threshold. Non-refundable. Verify current limits. " + VERIFY_IRS,
          ["AGI below threshold", "retirement contribution"], ["contribution records"], VERIFY_IRS),

    # ── Family & Dependents ───────────────────────────────────────────
    _rule("US-2026-child-tax-credit", "US", 2026, "family",
          "Child Tax Credit (IRC §24) — potentially relevant",
          "Credit per qualifying child under 17. Phaseout begins at $400K MFJ/$200K other. Verify current amounts. " + VERIFY_IRS,
          ["qualifying child under 17"], ["SSN for each child"], VERIFY_IRS),
    _rule("US-2026-child-care-credit", "US", 2026, "family",
          "Child and Dependent Care Credit (IRC §21) — potentially relevant",
          "Credit for work-related care expenses for children under 13 or disabled dependents. Percentage varies by AGI. " + VERIFY_IRS,
          ["qualifying dependent", "work-related care"], ["care provider receipts", "EIN/SSN"], VERIFY_IRS),
    _rule("US-2026-adoption-credit", "US", 2026, "family",
          "Adoption Credit (IRC §23) — potentially relevant",
          "Credit for qualified adoption expenses. Refundable portion may apply. Verify current limits. " + VERIFY_IRS,
          ["qualified adoption"], ["adoption documents", "expense receipts"], VERIFY_IRS),
    _rule("US-2026-dependent-exemption", "US", 2026, "family",
          "Dependent exemptions — currently suspended",
          "Personal exemptions are suspended through 2025 under TCJA. Verify whether extended. " + VERIFY_IRS,
          ["dependents"], [], VERIFY_IRS),

    # ── Education ─────────────────────────────────────────────────────
    _rule("US-2026-american-opportunity", "US", 2026, "education",
          "American Opportunity Tax Credit (IRC §25A) — potentially relevant",
          "Up to $2,500/student for first 4 years of undergrad. 40% refundable. Income phaseouts apply. " + VERIFY_IRS,
          ["enrolled at least half-time", "first 4 years of college"], ["Form 1098-T"], VERIFY_IRS),
    _rule("US-2026-lifetime-learning", "US", 2026, "education",
          "Lifetime Learning Credit (IRC §25A) — potentially relevant",
          "Up to $2,000 per return for tuition and fees. No limit on years. Income phaseouts. " + VERIFY_IRS,
          ["qualified education expenses"], ["Form 1098-T"], VERIFY_IRS),
    _rule("US-2026-529-plan", "US", 2026, "education",
          "529 Education Savings Plan — strategic opportunity",
          "Tax-free growth and withdrawals for qualified education expenses. Up to $10,000/year for K-12 tuition. " + VERIFY_IRS,
          ["529 plan account"], ["529 distribution statements"], VERIFY_IRS),
    _rule("US-2026-employer-education", "US", 2026, "education",
          "Employer education assistance (IRC §127) — potentially relevant",
          "Up to $5,250/year employer-provided education assistance is tax-free. Verify current limit. " + VERIFY_IRS,
          ["employer education benefit"], ["employer documentation"], VERIFY_IRS),

    # ── Investment & Capital Gains ────────────────────────────────────
    _rule("US-2026-tax-loss-harvesting", "US", 2026, "investments",
          "Tax-loss harvesting (IRC §1211/§1212) — strategic opportunity",
          "Offset capital gains with capital losses. Up to $3,000 net loss deduction against ordinary income. Wash sale rules apply. " + VERIFY_IRS,
          ["investment accounts with losses"], ["1099-B", "cost basis records"], VERIFY_IRS),
    _rule("US-2026-capital-gains-rates", "US", 2026, "investments",
          "Long-term capital gains rates (IRC §1(h)) — strategic opportunity",
          "Long-term gains taxed at 0%, 15%, or 20% depending on income. Net Investment Income Tax of 3.8% may apply. " + VERIFY_IRS,
          ["investment income"], ["1099-B", "1099-DIV"], VERIFY_IRS),
    _rule("US-2026-investment-interest", "US", 2026, "investments",
          "Investment interest expense (IRC §163(d)) — potentially relevant",
          "Deductible up to net investment income. Carryforward unused amounts. " + VERIFY_IRS,
          ["investment interest expense", "net investment income"], ["brokerage statements"], VERIFY_IRS),
    _rule("US-2026-qualified-dividends", "US", 2026, "investments",
          "Qualified dividend tax rates (IRC §1(h)) — strategic opportunity",
          "Qualified dividends taxed at capital gains rates (0/15/20%) rather than ordinary income rates. " + VERIFY_IRS,
          ["dividend income"], ["1099-DIV"], VERIFY_IRS),
    _rule("US-2026-qualified-business-income", "US", 2026, "business",
          "QBI deduction (IRC §199A) — potentially relevant",
          "Up to 20% deduction for qualified business income from pass-through entities. Income thresholds and W-2 limits apply. " + VERIFY_IRS,
          ["pass-through business income"], ["Schedule K-1", "business records"], VERIFY_IRS),

    # ── Self-Employment & Business ────────────────────────────────────
    _rule("US-2026-se-tax-deduction", "US", 2026, "business",
          "Self-employment tax deduction (IRC §164(f)) — potentially relevant",
          "Deductible portion (50%) of self-employment tax. Above-the-line deduction. " + VERIFY_IRS,
          ["self-employment income"], ["Schedule SE", "Schedule C"], VERIFY_IRS),
    _rule("US-2026-se-health-insurance", "US", 2026, "business",
          "Self-employed health insurance deduction (IRC §162(l)) — potentially relevant",
          "Above-the-line deduction for health insurance premiums if not eligible for employer plan. " + VERIFY_IRS,
          ["self-employment income", "no employer coverage"], ["premium payments", "Form 1095-A/B/C"], VERIFY_IRS),
    _rule("US-2026-business-expenses", "US", 2026, "business",
          "Business expenses (IRC §162) — potentially relevant",
          "Ordinary and necessary business expenses are deductible. Must be directly related to business. " + VERIFY_IRS,
          ["self-employment or business income"], ["receipts", "business records"], VERIFY_IRS),
    _rule("US-2026-section-179", "US", 2026, "business",
          "Section 179 expensing (IRC §179) — potentially relevant",
          "Immediate expensing of qualifying business assets up to annual limit. Phaseout begins at spending threshold. " + VERIFY_IRS,
          ["business asset purchase"], ["invoices", "asset records"], VERIFY_IRS),
    _rule("US-2026-depreciation", "US", 2026, "business",
          "MACRS depreciation (IRC §167/§168) — potentially relevant",
          "Accelerated depreciation for business assets. Bonus depreciation percentage changing yearly. " + VERIFY_IRS,
          ["business asset purchase"], ["asset records", "depreciation schedules"], VERIFY_IRS),
    _rule("US-2026-startup-costs", "US", 2026, "business",
          "Startup costs (IRC §195) — potentially relevant",
          "Deduct up to $5,000 in startup costs in year one (reduced if costs exceed $50K). Remainder amortized over 180 months. " + VERIFY_IRS,
          ["new business startup"], ["startup expense records"], VERIFY_IRS),
    _rule("US-2026-home-office-business", "US", 2026, "business",
          "Home office — self-employed (IRC §168(f)(1)) — potentially relevant",
          "Dedicate space exclusively for business. Simplified method ($5/sqft, max 300sqft) or actual expenses. " + VERIFY_IRS,
          ["exclusive use space", "self-employment income"], ["expense records", "photos"], VERIFY_IRS),
    _rule("US-2026-vehicle-expenses", "US", 2026, "business",
          "Vehicle expenses (IRC §162/§274) — potentially relevant",
          "Standard mileage rate or actual expenses for business use of vehicle. Must maintain mileage log. " + VERIFY_IRS,
          ["business vehicle use"], ["mileage log", "vehicle expenses"], VERIFY_IRS),
    _rule("US-2026-rental-expenses", "US", 2026, "business",
          "Rental property expenses (IRC §212/§274) — potentially relevant",
          "Mortgage interest, property tax, depreciation, repairs, insurance deductible against rental income. " + VERIFY_IRS,
          ["rental property income"], ["rental records", "expense receipts"], VERIFY_IRS),
    _rule("US-2026-bad-debt", "US", 2026, "business",
          "Business bad debt (IRC §166) — potentially relevant",
          "Deduct debts that become worthless during the tax year. Must have been included in income or be directly related to business. " + VERIFY_IRS,
          ["uncollectible business debt"], ["debt records", "collection attempts"], VERIFY_IRS),
    _rule("US-2026-rd-credit", "US", 2026, "business",
          "Research & Development Credit (IRC §41) — potentially relevant",
          "Credit for qualified research expenses. Small business alternative credit available. " + VERIFY_IRS,
          ["qualified R&D expenses"], ["research records", "expense documentation"], VERIFY_IRS),

    # ── Energy & Environment ──────────────────────────────────────────
    _rule("US-2026-energy-efficient-home", "US", 2026, "energy",
          "Energy Efficient Home Improvement Credit (IRC §25C) — potentially relevant",
          "Credit for qualifying energy-efficient home improvements (windows, doors, insulation, HVAC). Annual limits apply. " + VERIFY_IRS,
          ["energy-efficient home improvements"], ["receipts", "manufacturer certifications"], VERIFY_IRS),
    _rule("US-2026-solar-credit", "US", 2026, "energy",
          "Residential Clean Energy Credit (IRC §25D) — potentially relevant",
          "30% credit for solar electric, solar water heating, fuel cells, wind energy. No annual cap. Carryforward available. " + VERIFY_IRS,
          ["solar or clean energy installation"], ["installation invoices", "manufacturer certifications"], VERIFY_IRS),
    _rule("US-2026-ev-credit", "US", 2026, "energy",
          "Clean Vehicle Credit (IRC §30D) — potentially relevant",
          "Up to $7,500 credit for new EVs meeting assembly and battery requirements. Income and price caps apply. " + VERIFY_IRS,
          ["new qualifying EV purchase"], ["vehicle identification", "purchase documents"], VERIFY_IRS),
    _rule("US-2026-used-ev-credit", "US", 2026, "energy",
          "Used Clean Vehicle Credit (IRC §25E) — potentially relevant",
          "Up to $4,000 credit for used EVs from dealers. Income cap and price cap apply. " + VERIFY_IRS,
          ["used qualifying EV purchase from dealer"], ["purchase documents", "dealer records"], VERIFY_IRS),

    # ── Other Deductions & Credits ────────────────────────────────────
    _rule("US-2026-educator-expenses", "US", 2026, "education",
          "Educator expenses (IRC §62(c)) — potentially relevant",
          "Above-the-line deduction for K-12 teachers spending on classroom supplies. Verify current limit. " + VERIFY_IRS,
          ["K-12 educator"], ["expense receipts"], VERIFY_IRS),
    _rule("US-2026-alimony", "US", 2026, "family",
          "Alimony payments (IRC §215) — check agreement date",
          "Deductible for agreements finalized before 2019. Post-2018 alimony is not deductible by payer nor taxable to recipient. " + VERIFY_IRS,
          ["pre-2019 divorce agreement"], ["alimony payment records"], VERIFY_IRS),
    _rule("US-2026-mortgage-points", "US", 2026, "housing",
          "Mortgage points (IRC §163/§461) — potentially relevant",
          "Points paid on purchase mortgage fully deductible in year paid. Refinance points amortized over loan life. " + VERIFY_IRS,
          ["mortgage closing documents"], ["Form 1098", "HUD-1 settlement"], VERIFY_IRS),
    _rule("US-2026-state-refund", "US", 2026, "housing",
          "State tax refund recovery (IRC §111) — potentially relevant",
          "If you deducted state taxes last year and received a refund, the refund may be taxable this year. " + VERIFY_IRS,
          ["state tax refund received", "prior year itemized deductions"], ["Form 1099-G"], VERIFY_IRS),
    _rule("US-2026-capital-loss-carryforward", "US", 2026, "investments",
          "Capital loss carryforward (IRC §1212) — potentially relevant",
          "Unused capital losses carry forward indefinitely. Track across years for optimal harvesting. " + VERIFY_IRS,
          ["prior year capital losses"], ["Schedule D", "prior year returns"], VERIFY_IRS),
    _rule("US-2026-estimated-tax", "US", 2026, "compliance",
          "Estimated tax payments (IRC §6654) — compliance requirement",
          "Quarterly estimated tax payments required if expecting $1,000+ tax liability. Underpayment penalties apply. " + VERIFY_IRS,
          ["self-employment income", "withholding below liability"], ["1040-ES", "payment records"], VERIFY_IRS),
    _rule("US-2026-safe-harbor", "US", 2026, "compliance",
          "Estimated tax safe harbor — strategic opportunity",
          "Avoid underpayment penalty by paying 100% of prior year tax (110% if AGI > $150K) or 90% of current year. " + VERIFY_IRS,
          ["prior year tax liability"], ["prior year return"], VERIFY_IRS),
    _rule("US-2026-foreign-tax-credit", "US", 2026, "investments",
          "Foreign Tax Credit (IRC §901) — potentially relevant",
          "Credit for foreign taxes paid on foreign-source income. Avoids double taxation. " + VERIFY_IRS,
          ["foreign income or investments"], ["foreign tax statements", "Form 1116"], VERIFY_IRS),
    _rule("US-2026-net-investment-income", "US", 2026, "investments",
          "Net Investment Income Tax (IRC §1411) — compliance awareness",
          "3.8% surtax on net investment income if MAGI exceeds $200K single / $250K MFJ. " + VERIFY_IRS,
          ["investment income", "MAGI above threshold"], ["investment statements"], VERIFY_IRS),

    # ── Health & Insurance (additional) ──────────────────────────────
    _rule("US-2026-cobra", "US", 2026, "health",
          "COBRA continuation coverage deduction — potentially relevant",
          "COBRA premiums paid for former employer coverage may be deductible as medical expenses if you itemize. Subject to 7.5% AGI floor. " + VERIFY_IRS,
          ["COBRA election", "no employer coverage"], ["COBRA premium statements"], VERIFY_IRS),
    _rule("US-2026-long-term-care", "US", 2026, "health",
          "Long-term care insurance deduction (IRC §213(d)(10)) — potentially relevant",
          "Accelerated long-term care benefits and employer-provided LTC coverage may be excludable. Self-employed can deduct premiums. Verify age-based limits. " + VERIFY_IRS,
          ["long-term care insurance policy"], ["premium statements"], VERIFY_IRS),
    _rule("US-2026-archer-msa", "US", 2026, "health",
          "Archer MSA contributions (IRC §220) — potentially relevant",
          "Tax-deductible contributions to Archer MSAs for self-employed or small-employer employees. Triple tax advantage similar to HSA. Annual limits apply. " + VERIFY_IRS,
          ["high-deductible plan", "Archer MSA eligible"], ["Form 5498-MSA"], VERIFY_IRS),
    _rule("US-2026-medicare-premiums", "US", 2026, "health",
          "Medicare premiums deduction (self-employed) — potentially relevant",
          "Self-employed individuals may deduct Medicare Part B, Part D, and Medigap premiums as health insurance premiums above the line. " + VERIFY_IRS,
          ["self-employment income", "enrolled in Medicare"], ["Medicare premium statements"], VERIFY_IRS),

    # ── Disability & Losses ─────────────────────────────────────────
    _rule("US-2026-disability-income", "US", 2026, "income",
          "Disability income exclusion — compliance awareness",
          "Employer-provided disability benefits may be partially excludable if premiums were paid with after-tax dollars. Social Security disability is taxable above threshold. " + VERIFY_IRS,
          ["disability income", "premium payment basis"], ["Form 1099-R", "SSA-1099"], VERIFY_IRS),
    _rule("US-2026-casualty-loss", "US", 2026, "income",
          "Casualty and theft losses (IRC §165) — check current rules",
          "Federally declared disaster area casualty losses may be deductible. Each loss must exceed $100 and total losses exceed 10% of AGI (if not suspended). " + VERIFY_IRS,
          ["federally declared disaster loss"], ["loss documentation", "insurance claims"], VERIFY_IRS),
    _rule("US-2026-flood-insurance-rental", "US", 2026, "business",
          "Flood insurance for rental property — potentially relevant",
          "Flood insurance premiums for rental property are deductible as rental expenses on Schedule E. Verify current deductibility. " + VERIFY_IRS,
          ["rental property with flood insurance"], ["insurance premium statements"], VERIFY_IRS),

    # ── Estate & Gift ─────────────────────────────────────────────────
    _rule("US-2026-estate-exemption", "US", 2026, "estate",
          "Estate tax exemption amount — compliance awareness",
          "Federal estate tax exemption shields a large portion of estates from taxation. Verify the current exemption amount and sunset provisions. " + VERIFY_IRS,
          ["estate planning", "total estate value"], ["estate valuation records"], VERIFY_IRS),
    _rule("US-2026-lifetime-gift", "US", 2026, "estate",
          "Lifetime gift tax exemption — strategic opportunity",
          "Unified credit allows lifetime gifts up to the estate tax exemption amount without gift tax. Gifts above annual exclusion reduce lifetime exemption. " + VERIFY_IRS,
          ["gifts exceeding annual exclusion"], ["gift tax return records"], VERIFY_IRS),
    _rule("US-2026-annual-gift", "US", 2026, "estate",
          "Annual gift tax exclusion — potentially relevant",
          "You can give up to the annual exclusion per recipient without filing a gift tax return. Verify the current exclusion amount. " + VERIFY_IRS,
          ["gifts to individuals"], ["gift records"], VERIFY_IRS),
    _rule("US-2026-529-superfunding", "US", 2026, "estate",
          "529 superfunding (5-year front-loading) — strategic opportunity",
          "Lump-sum contributions of up to 5 years of annual exclusion to a 529 plan without gift tax. Accelerates education funding. " + VERIFY_IRS,
          ["529 plan account"], ["contribution records"], VERIFY_IRS),

    # ── Foreign Income & Credits ──────────────────────────────────────
    _rule("US-2026-foreign-earned-income", "US", 2026, "investments",
          "Foreign earned income exclusion (IRC §911) — potentially relevant",
          "Exclude foreign earned income up to the annual exclusion if you meet bona fide residence or physical presence test. Verify current exclusion amount. " + VERIFY_IRS,
          ["foreign earned income", "qualifying residence/presence"], ["Form 2555"], VERIFY_IRS),
    _rule("US-2026-foreign-housing", "US", 2026, "investments",
          "Foreign housing exclusion/deduction — potentially relevant",
          "Exclude or deduct qualified housing expenses abroad above a base amount. Limits vary by location. " + VERIFY_IRS,
          ["foreign housing expenses", "qualifying foreign residence"], ["Form 2555"], VERIFY_IRS),
    _rule("US-2026-fbar", "US", 2026, "compliance",
          "FBAR/FinCEN 114 reporting — compliance requirement",
          "Report foreign financial accounts if aggregate value exceeds $10,000 at any time during the year. Filed electronically via BSA E-Filing. " + VERIFY_IRS,
          ["foreign financial accounts"], ["account statements"], VERIFY_IRS),
    _rule("US-2026-fatca", "US", 2026, "compliance",
          "FATCA Form 8938 reporting — compliance requirement",
          "Report specified foreign financial assets exceeding thresholds based on filing status and residence. Thresholds higher than FBAR. " + VERIFY_IRS,
          ["foreign financial assets above threshold"], ["foreign account statements"], VERIFY_IRS),
    _rule("US-2026-foreign-retirement", "US", 2026, "investments",
          "Foreign retirement account (treaty-dependent) — potentially relevant",
          "Tax treatment of foreign retirement accounts depends on applicable tax treaty. May be deferrable or taxable annually. Verify treaty provisions. " + VERIFY_IRS,
          ["foreign retirement account", "applicable tax treaty"], ["foreign retirement account statements"], VERIFY_IRS),

    # ── Capital Gains & Investment (additional) ───────────────────────
    _rule("US-2026-installment-sale", "US", 2026, "investments",
          "Installment sale reporting (IRC §453) — potentially relevant",
          "Report gain from installment sales proportionally as payments are received. Defers gain recognition over payment period. " + VERIFY_IRS,
          ["installment sale transaction"], ["installment sale contract", "payment records"], VERIFY_IRS),
    _rule("US-2026-opportunity-zone", "US", 2026, "investments",
          "Qualified Opportunity Zone deferral (IRC §1400Z) — strategic opportunity",
          "Defer and potentially reduce capital gains by investing in Qualified Opportunity Zone funds. Verify current rules and deadlines. " + VERIFY_IRS,
          ["capital gain from sale", "QOZ fund investment"], ["fund investment records"], VERIFY_IRS),
    _rule("US-2026-like-kind", "US", 2026, "investments",
          "Like-kind exchange (IRC §1031, real property only) — potentially relevant",
          "Defer gain on exchange of real property held for business or investment. Post-TCJA, like-kind is limited to real property. " + VERIFY_IRS,
          ["real property exchange"], ["exchange documentation", "closing statements"], VERIFY_IRS),
    _rule("US-2026-wash-sale", "US", 2026, "investments",
          "Wash sale rule (IRC §1091) — compliance awareness",
          "Losses on securities are disallowed if substantially identical securities are purchased within 30 days before or after sale. Loss is added to basis of replacement shares. " + VERIFY_IRS,
          ["investment sale at loss"], ["brokerage statements"], VERIFY_IRS),
    _rule("US-2026-net-capital-gain", "US", 2026, "investments",
          "Net capital gain worksheet — potentially relevant",
          "Use the net capital gain worksheet to determine if you qualify for the 0% capital gains rate. Based on taxable income and net capital gains. " + VERIFY_IRS,
          ["capital gains and losses"], ["Schedule D"], VERIFY_IRS),
    _rule("US-2026-qualified-small-business", "US", 2026, "investments",
          "QSBS exclusion (IRC §1202) — potentially relevant",
          "Exclude up to 100% of gain on Qualified Small Business Stock held more than 5 years. Subject to per-issuer limits and holding period. " + VERIFY_IRS,
          ["QSBS stock", "held >5 years"], ["stock purchase records", "corporate records"], VERIFY_IRS),
    _rule("US-2026-83b-election", "US", 2026, "investments",
          "Section 83(b) election for restricted stock — strategic opportunity",
          "Elect to pay tax on restricted stock at grant date rather than vesting date. May reduce total tax if stock appreciates. Time-sensitive filing. " + VERIFY_IRS,
          ["restricted stock grant"], ["83(b) election filed"], VERIFY_IRS),

    # ── Self-Employment & Business (additional) ───────────────────────
    _rule("US-2026-inventory-method", "US", 2026, "business",
          "Inventory method selection (IRC §471) — potentially relevant",
          "Choose between FIFO, LIFO, or other IRS-approved methods for inventory valuation. Method affects COGS and taxable income. " + VERIFY_IRS,
          ["inventory-based business"], ["inventory records"], VERIFY_IRS),
    _rule("US-2026-accounting-method", "US", 2026, "business",
          "Cash vs accrual accounting — potentially relevant",
          "Cash method recognizes income when received; accrual when earned. Small business exception may allow cash method. Verify current thresholds. " + VERIFY_IRS,
          ["business income"], ["business financial records"], VERIFY_IRS),
    _rule("US-2026-business-use-home", "US", 2026, "business",
          "Home office allocation methods (detailed) — potentially relevant",
          "Square footage method: business sqft / total sqft times total home expenses. Expense method: based on room usage. Both require exclusive use. " + VERIFY_IRS,
          ["exclusive use home office"], ["floor plan", "expense records"], VERIFY_IRS),
    _rule("US-2026-cooperative-income", "US", 2026, "business",
          "Cooperative income allocation — potentially relevant",
          "Patronage dividends from cooperatives may be partially excludable. Verify current exclusion limits and allocation rules. " + VERIFY_IRS,
          ["cooperative membership"], ["patronage dividend statements"], VERIFY_IRS),
    _rule("US-2026-passive-loss", "US", 2026, "business",
          "Passive activity loss rules (IRC §469) — compliance awareness",
          "Losses from passive activities can only offset passive income. Real estate has special $25K allowance for active participants (income limited). " + VERIFY_IRS,
          ["passive activity income/loss"], ["Schedule E", "K-1"], VERIFY_IRS),
    _rule("US-2026-hobby-loss", "US", 2026, "business",
          "Hobby loss rules (IRC §183) — compliance awareness",
          "Activity not engaged for profit may only deduct expenses up to income. Presumed hobby if profitable in 3 of 5 years. Verify current rules. " + VERIFY_IRS,
          ["activity with losses", "not-for-profit intent"], ["activity records"], VERIFY_IRS),
    _rule("US-2026-s-corp-reasonable", "US", 2026, "business",
          "S-Corp reasonable compensation — compliance awareness",
          "S-Corp shareholder-employees must receive reasonable compensation for services. IRS scrutinizes low salaries to avoid FICA taxes. " + VERIFY_IRS,
          ["S-Corp shareholder-employee"], ["payroll records"], VERIFY_IRS),
    _rule("US-2026-partnership-k1", "US", 2026, "business",
          "Partnership K-1 reporting — compliance awareness",
          "Partnership income, deductions, and credits flow through to partners via Schedule K-1. Each partner reports their share on personal return. " + VERIFY_IRS,
          ["partnership interest"], ["Schedule K-1"], VERIFY_IRS),
    _rule("US-2026-business-interest", "US", 2026, "business",
          "Business interest expense limitation (IRC §163(j)) — compliance awareness",
          "Business interest deduction limited to 30% of adjusted taxable income for large businesses. Small business exception may apply. " + VERIFY_IRS,
          ["business with interest expense"], ["financial statements"], VERIFY_IRS),

    # ── Family & Credits (additional) ─────────────────────────────────
    _rule("US-2026-earned-income-credit", "US", 2026, "family",
          "Earned Income Tax Credit (IRC §32) — potentially relevant",
          "Refundable credit for low-to-moderate income workers. Amount depends on income, filing status, and number of qualifying children. Verify current thresholds. " + VERIFY_IRS,
          ["earned income below threshold", "qualifying children (or no children)"], ["W-2", "Schedule E"], VERIFY_IRS),
    _rule("US-2026-additional-child-credit", "US", 2026, "family",
          "Additional Child Tax Credit (refundable) — potentially relevant",
          "Refundable portion of the Child Tax Credit for taxpayers who owe less tax than the credit amount. Verify current rules and phaseouts. " + VERIFY_IRS,
          ["qualifying child", "tax liability less than credit"], ["Form 8812"], VERIFY_IRS),
    _rule("US-2026-adoption-credit-detail", "US", 2026, "family",
          "Adoption Credit detailed limits (IRC §23) — potentially relevant",
          "Credit for qualified adoption expenses up to the annual limit. Phaseout applies at higher incomes. Verify current limits and eligible expenses. " + VERIFY_IRS,
          ["qualified adoption expense"], ["adoption records", "expense receipts"], VERIFY_IRS),
    _rule("US-2026-foster-care-payments", "US", 2026, "family",
          "Foster care payments exclusion — potentially relevant",
          "Foster care payments for care of qualifying children may be excludable from income up to certain limits. Verify current rules. " + VERIFY_IRS,
          ["foster care arrangement"], ["payment records"], VERIFY_IRS),
    _rule("US-2026-injured-spouse", "US", 2026, "compliance",
          "Injured spouse relief — potentially relevant",
          "If your refund is offset for your spouse's past-due obligations, you may recover your portion by filing Form 8379. " + VERIFY_IRS,
          ["joint return with offset risk"], ["Form 8379"], VERIFY_IRS),
    _rule("US-2026-head-of-household", "US", 2026, "filing",
          "Head of Household filing status requirements — compliance awareness",
          "Unmarried taxpayer maintaining a home for a qualifying person. More favorable standard deduction and tax brackets than Single. " + VERIFY_IRS,
          ["unmarried", "qualifying person in home"], ["support documentation"], VERIFY_IRS),
    _rule("US-2026-qualifying-widow", "US", 2026, "filing",
          "Qualifying Widow(er) filing status — compliance awareness",
          "Surviving spouse may use Married Filing Jointly rates for 2 years after spouse's death if maintaining a dependent home. " + VERIFY_IRS,
          ["spouse died within 2 years", "dependent in home"], ["death certificate", "dependent records"], VERIFY_IRS),

    # ── Housing & Property (additional) ───────────────────────────────
    _rule("US-2026-primary-residence", "US", 2026, "housing",
          "Primary residence capital gains exclusion (IRC §121) — potentially relevant",
          "Exclude up to $250K (single) or $500K (MFJ) gain on sale of primary residence owned and used 2 of last 5 years. " + VERIFY_IRS,
          ["primary residence sale", "owned and used 2+ years"], ["closing documents", "basis records"], VERIFY_IRS),
    _rule("US-2026-second-home", "US", 2026, "housing",
          "Second home mortgage interest rules — potentially relevant",
          "Mortgage interest on a second home is deductible if you itemize, subject to acquisition debt limits. Verify current limits. " + VERIFY_IRS,
          ["second home with mortgage"], ["Form 1098"], VERIFY_IRS),
    _rule("US-2026-rental-deduction-limitation", "US", 2026, "business",
          "Rental deduction limitation (passive activity) — compliance awareness",
          "Rental real estate losses generally limited to passive income unless you qualify as a real estate professional or under the $25K exception. " + VERIFY_IRS,
          ["rental property with losses"], ["Schedule E"], VERIFY_IRS),
    _rule("US-2026-real-estate-professional", "US", 2026, "business",
          "Real estate professional status (IRC §469(c)(7)) — potentially relevant",
          "Qualify as real estate professional to deduct rental losses against active income. Requires 750+ hours and material participation. " + VERIFY_IRS,
          ["real estate activity hours"], ["time logs", "rental activity records"], VERIFY_IRS),
    _rule("US-2026-cost-segment", "US", 2026, "business",
          "Cost segregation study benefits — strategic opportunity",
          "Reclassify building components to shorter depreciation lives. Accelerates deductions on commercial or rental property. " + VERIFY_IRS,
          ["commercial or rental property purchase"], ["cost segregation study"], VERIFY_IRS),

    # ── Retirement Advanced ───────────────────────────────────────────
    _rule("US-2026-backdoor-roth", "US", 2026, "retirement",
          "Backdoor Roth IRA strategy — strategic opportunity",
          "Contribute to non-deductible Traditional IRA then convert to Roth. May avoid income limits on direct Roth contributions. Pro-rata rules apply. " + VERIFY_IRS,
          ["income above Roth IRA limit", "low pre-tax IRA balance"], ["conversion records"], VERIFY_IRS),
    _rule("US-2026-mega-backdoor-roth", "US", 2026, "retirement",
          "Mega backdoor Roth (after-tax 401k) — strategic opportunity",
          "Contribute after-tax dollars to 401(k) beyond the $23,500 limit, then convert to Roth in-plan or roll to Roth IRA. Plan must allow. " + VERIFY_IRS,
          ["401(k) with after-tax contributions", "in-plan Roth conversion"], ["401(k) statements"], VERIFY_IRS),
    _rule("US-2026-rmd", "US", 2026, "retirement",
          "Required Minimum Distribution rules (IRC §401(a)(9)) — compliance requirement",
          "Must begin RMDs by April 1 of year after turning 73 (SECURE 2.0). Failure to take RMD triggers 25% excise tax (10% if corrected timely). " + VERIFY_IRS,
          ["age 73+ or inherited IRA"], ["retirement account statements"], VERIFY_IRS),
    _rule("US-2026-rmd-still-working", "US", 2026, "retirement",
          "RMD exception for still-working — strategic opportunity",
          "If still working at age 73+ with an employer 401(k), you may delay RMDs from that plan until retirement. Does not apply to IRAs. " + VERIFY_IRS,
          ["age 73+ and still working", "employer 401(k)"], ["employment records"], VERIFY_IRS),
    _rule("US-2026-inherited-ira", "US", 2026, "retirement",
          "Inherited IRA distribution rules (SECURE Act) — compliance awareness",
          "Non-spouse beneficiaries must generally withdraw all inherited IRA funds within 10 years. Spouses have more options. Verify current rules. " + VERIFY_IRS,
          ["inherited IRA", "beneficiary designation"], ["inheritance documentation"], VERIFY_IRS),
    _rule("US-2026-457b", "US", 2026, "retirement",
          "Government 457(b) plan contributions — potentially relevant",
          "Tax-deferred contributions to governmental 457(b) plans. Separate limit from 401(k). Catch-up available for last 3 years before retirement. " + VERIFY_IRS,
          ["governmental 457(b) plan"], ["contribution statements"], VERIFY_IRS),
    _rule("US-2026-simple-ira", "US", 2026, "retirement",
          "SIMPLE IRA contributions and rules — potentially relevant",
          "Employer and employee contributions to SIMPLE IRAs. Lower limits than 401(k) but easier administration. Verify current limits. " + VERIFY_IRS,
          ["SIMPLE IRA plan"], ["contribution statements"], VERIFY_IRS),
    _rule("US-2026-qualified-plan-loan", "US", 2026, "retirement",
          "Qualified plan loan rules — potentially relevant",
          "Borrow up to 50% of vested balance (max $50K) from qualified plan. Repayment with interest required. Rules vary by plan. " + VERIFY_IRS,
          ["qualified plan with loan provision"], ["plan documents", "loan records"], VERIFY_IRS),

    # ── Income Adjustments ────────────────────────────────────────────
    _rule("US-2026-magia-deduction", "US", 2026, "education",
          "Student loan interest MAGI deduction — potentially relevant",
          "Above-the-line deduction phases out based on MAGI. Verify current phaseout ranges for your filing status. " + VERIFY_IRS,
          ["student loan interest paid", "MAGI within phaseout"], ["Form 1098-E"], VERIFY_IRS),
    _rule("US-2026-teacher-supply", "US", 2026, "education",
          "Educator supply deduction (enhanced rules) — potentially relevant",
          "K-12 teachers can deduct unreimbursed classroom expenses. Verify current limit and whether enhanced amounts apply. " + VERIFY_IRS,
          ["K-12 educator", "unreimbursed supplies"], ["expense receipts"], VERIFY_IRS),
    _rule("US-2026-jury-duty-pay", "US", 2026, "income",
          "Jury duty pay taxation — compliance awareness",
          "Jury duty pay is taxable income. If employer continues salary and you remit jury pay to employer, income nets out. " + VERIFY_IRS,
          ["jury duty service"], ["jury duty pay statement"], VERIFY_IRS),
    _rule("US-2026-prize-award", "US", 2026, "income",
          "Prize and award income (IRC §74) — compliance awareness",
          "Prize and award income is generally taxable. Charitable organization awards may be excluded if no substantial contributor status. " + VERIFY_IRS,
          ["prize or award received"], ["Form 1099-MISC"], VERIFY_IRS),
    _rule("US-2026-debt-cancellation", "US", 2026, "income",
          "Debt cancellation income (IRC §61(a)(11)) — compliance awareness",
          "Cancelled debt may be taxable as income. Insolvency or bankruptcy exceptions may apply. Verify exclusions. " + VERIFY_IRS,
          ["cancelled debt"], ["Form 1099-C"], VERIFY_IRS),
    _rule("US-2026-statute-limitations", "US", 2026, "compliance",
          "Statute of limitations on tax assessments — compliance awareness",
          "IRS generally has 3 years to assess additional tax; 6 years if income underreported by 25%+; unlimited for fraud. " + VERIFY_IRS,
          ["tax return filed"], ["prior returns"], VERIFY_IRS),
    _rule("US-2026-amended-return", "US", 2026, "compliance",
          "Amended return rules (Form 1040-X) — potentially relevant",
          "File Form 1040-X to correct errors or claim missed deductions/credits. Generally within 3 years of original filing. " + VERIFY_IRS,
          ["need to amend prior return"], ["Form 1040-X", "supporting documents"], VERIFY_IRS),
    _rule("US-2026-extension", "US", 2026, "compliance",
          "Filing extension rules — compliance awareness",
          "Automatic 6-month extension to file (not pay). Must estimate and pay any tax owed by original deadline to avoid penalties. " + VERIFY_IRS,
          ["need additional filing time"], ["Form 4868"], VERIFY_IRS),
    _rule("US-2026-underpayment-penalty", "US", 2026, "compliance",
          "Underpayment penalty calculation details — compliance awareness",
          "Penalty based on underpayment amount times days outstanding times federal short-term rate plus 3%. Calculated quarterly. " + VERIFY_IRS,
          ["underpaid estimated taxes"], ["Form 2210"], VERIFY_IRS),
    _rule("US-2026-estimated-tax-safe-harbor", "US", 2026, "compliance",
          "Estimated tax safe harbor detailed rules — strategic opportunity",
          "Pay 100% of prior year tax (110% if AGI > $150K) or 90% of current year tax to avoid underpayment penalty. " + VERIFY_IRS,
          ["prior year AGI and tax"], ["prior year return"], VERIFY_IRS),

    # ── Filing & Compliance ───────────────────────────────────────────
    _rule("US-2026-identity-theft", "US", 2026, "compliance",
          "Tax-related identity theft (Form 14039) — compliance awareness",
          "If you suspect tax-related identity theft, file Form 14039 with the IRS. May delay processing. " + VERIFY_IRS,
          ["suspected identity theft"], ["Form 14039"], VERIFY_IRS),
    _rule("US-2026-innocent-spouse", "US", 2026, "compliance",
          "Innocent spouse relief (IRC §6015) — potentially relevant",
          "Relief from joint tax liability if spouse's errors caused the deficiency. Three types of relief available. " + VERIFY_IRS,
          ["joint return with spouse error"], ["Form 8857"], VERIFY_IRS),
    _rule("US-2026-offshore-disclosure", "US", 2026, "compliance",
          "Offshore voluntary disclosure — potentially relevant",
          "Programs available to come into compliance with offshore account reporting. Penalties may be reduced. Consult a professional. " + VERIFY_IRS,
          ["unreported foreign accounts"], ["offshore account records"], VERIFY_IRS),
    _rule("US-2026-irs-payment-plan", "US", 2026, "compliance",
          "IRS payment plan options — potentially relevant",
          "If you cannot pay your tax bill, short-term (120 days) or long-term installment plans are available. Interest and penalties continue to accrue. " + VERIFY_IRS,
          ["tax liability you cannot pay"], ["Form 9465"], VERIFY_IRS),
    _rule("US-2026-estimated-tax-electronic", "US", 2026, "compliance",
          "Electronic estimated tax payments — compliance awareness",
          "Use EFTPS or IRS Direct Pay for electronic estimated tax payments. Businesses with $100K+ must use EFTPS. " + VERIFY_IRS,
          ["estimated tax payments"], ["EFTPS enrollment"], VERIFY_IRS),
    _rule("US-2026-filing-requirements", "US", 2026, "filing",
          "Filing requirements thresholds — compliance awareness",
          "Filing required if gross income exceeds standard deduction plus exemptions for your filing status. Verify current thresholds. " + VERIFY_IRS,
          ["gross income"], ["income documentation"], VERIFY_IRS),
    _rule("US-2026-standard-deduction", "US", 2026, "filing",
          "Standard deduction amounts 2026 — compliance awareness",
          "Standard deduction amounts for Single, MFJ, MFS, HOH, and Qualifying Surviving Spouse. Verify current-year amounts. " + VERIFY_IRS,
          ["filing status"], [], VERIFY_IRS),
    _rule("US-2026-personal-exemption-status", "US", 2026, "filing",
          "Personal exemption status post-TCJA — compliance awareness",
          "Personal exemptions are currently zero (suspended through 2025 under TCJA). Verify whether extended or reinstated. " + VERIFY_IRS,
          ["tax return filed"], [], VERIFY_IRS),

    # ── Special Situations ────────────────────────────────────────────
    _rule("US-2026-gig-economy", "US", 2026, "business",
          "Gig economy / 1099 reporting — compliance awareness",
          "Income from gig work reported on Schedule C. Deductible business expenses. May owe self-employment tax. Verify current rules. " + VERIFY_IRS,
          ["1099 income"], ["Form 1099-NEC/MISC", "Schedule C"], VERIFY_IRS),
    _rule("US-2026-crypto-taxation", "US", 2026, "investments",
          "Cryptocurrency taxation (property rules) — compliance awareness",
          "Crypto treated as property for tax purposes. Every disposition is a taxable event. Capital gains rules apply. Verify current guidance. " + VERIFY_IRS,
          ["cryptocurrency transactions"], ["exchange records", "Form 8949"], VERIFY_IRS),
    _rule("US-2026-nft-taxation", "US", 2026, "investments",
          "NFT taxation specifics — compliance awareness",
          "NFTs taxed as property. Sale or exchange triggers capital gains/losses. Some NFTs may be collectibles subject to 28% rate. " + VERIFY_IRS,
          ["NFT transactions"], ["transaction records"], VERIFY_IRS),
    _rule("US-2026-staking-rewards", "US", 2026, "investments",
          "Staking rewards taxation — compliance awareness",
          "Staking rewards may be taxable as ordinary income when received. Subsequent value changes treated as capital gains/losses. " + VERIFY_IRS,
          ["crypto staking rewards"], ["staking reward records"], VERIFY_IRS),
    _rule("US-2026-deferred-compensation", "US", 2026, "income",
          "Nonqualified deferred compensation (§409A) — compliance awareness",
          "NQDC plans must meet §409A requirements. Taxed at vesting or distribution depending on plan terms. Early withdrawal penalties apply. " + VERIFY_IRS,
          ["nonqualified deferred compensation plan"], ["plan documents", "distribution records"], VERIFY_IRS),
    _rule("US-2026-supplemental-income", "US", 2026, "income",
          "Supplemental wage withholding rules — compliance awareness",
          "Supplemental wages (bonuses, commissions) subject to flat 22% withholding (37% over $1M). Employer may aggregate with regular wages. " + VERIFY_IRS,
          ["supplemental wages received"], ["Form W-2"], VERIFY_IRS),
    _rule("US-2026-bonus-withholding", "US", 2026, "income",
          "Bonus withholding rate (flat 22%) — compliance awareness",
          "Supplemental wages under $1M taxed at flat 22% for federal withholding. True tax rate depends on your marginal bracket. " + VERIFY_IRS,
          ["bonus or supplemental wages"], ["Form W-2"], VERIFY_IRS),
    _rule("US-2026-stock-compensation", "US", 2026, "investments",
          "Stock option taxation (ISO vs NSO) — potentially relevant",
          "ISOs may qualify for capital gains treatment if holding periods met. NSOs taxed as ordinary income at exercise. Verify current rules. " + VERIFY_IRS,
          ["stock option grant"], ["option exercise records", "Form 3921/3922"], VERIFY_IRS),
    _rule("US-2026-espp", "US", 2026, "investments",
          "Employee Stock Purchase Plan (§423) — potentially relevant",
          "Discount on employer stock may be partially excludable if holding period requirements met. Verify current rules. " + VERIFY_IRS,
          ["ESPP participation"], ["Form 3922"], VERIFY_IRS),
    _rule("US-2026-moving-expenses", "US", 2026, "income",
          "Moving expenses (military only post-TCJA) — compliance awareness",
          "Moving expense deduction currently limited to active-duty military. Verify current rules for other taxpayers. " + VERIFY_IRS,
          ["military service member"], ["moving expense receipts"], VERIFY_IRS),
    _rule("US-2026-jobs-act-opportunity-zone", "US", 2026, "investments",
          "Opportunity Zone fund details — strategic opportunity",
          "Invest capital gains in Qualified Opportunity Zone funds for deferral and potential exclusion of appreciation. Verify current deadlines. " + VERIFY_IRS,
          ["capital gain investment in QOZ fund"], ["fund investment records"], VERIFY_IRS),

    # ── Health & Insurance (expanded) ──────────────────────────────────
    _rule("US-2026-hsa-contribution-limits", "US", 2026, "health",
          "HSA contribution limits by coverage type — compliance awareness",
          "HSA contribution limits differ for self-only vs family coverage. Catch-up contributions available at age 55+. Verify current limits. " + VERIFY_IRS,
          ["HSA-eligible HDHP", "HSA account"], ["Form 5498-SA"], VERIFY_IRS),
    _rule("US-2026-hsa-qualified-expenses", "US", 2026, "health",
          "HSA qualified medical expenses (IRC §213(d)) — compliance awareness",
          "HSA funds used for non-qualified expenses are subject to income tax plus 20% penalty. Verify eligible expense list. " + VERIFY_IRS,
          ["HSA account", "medical expense"], ["receipts", "Form 1099-SA"], VERIFY_IRS),
    _rule("US-2026-ocha-deduction", "US", 2026, "health",
          "Other health coverage arrangements — potentially relevant",
          "Various employer health arrangements may affect deduction eligibility. Verify coordination between HSA, FSA, and other coverage. " + VERIFY_IRS,
          ["employer health plan"], ["plan documents"], VERIFY_IRS),
    _rule("US-2026-adhd-medical", "US", 2026, "health",
          "ADHD and related medical expense eligibility — compliance awareness",
          "Treatment for ADHD may qualify as deductible medical expense if prescribed. Educational costs for ADHD generally not deductible as medical. " + VERIFY_IRS,
          ["ADHD treatment expenses"], ["medical receipts", "prescriptions"], VERIFY_IRS),
    _rule("US-2026-fertility-expenses", "US", 2026, "health",
          "Fertility treatment expense deduction — potentially relevant",
          "Fertility treatments (IVF, IUI, etc.) qualify as medical expenses subject to 7.5% AGI floor. Donor eggs/sperm costs may be included. " + VERIFY_IRS,
          ["fertility treatment expenses"], ["medical receipts", "treatment records"], VERIFY_IRS),

    # ── Disability & Losses (expanded) ─────────────────────────────────
    _rule("US-2026-ssdi-taxation", "US", 2026, "income",
          "Social Security Disability Insurance taxation — compliance awareness",
          "SSDI benefits may be taxable if combined income exceeds threshold. Up to 85% of benefits may be taxable. " + VERIFY_IRS,
          ["SSDI benefits", "combined income above threshold"], ["SSA-1099"], VERIFY_IRS),
    _rule("US-2026-disability-credit", "US", 2026, "family",
          "Disability-related dependent care credits — potentially relevant",
          "Additional credits may be available for care of disabled dependents beyond standard child care credit. Verify eligibility. " + VERIFY_IRS,
          ["disabled dependent", "work-related care"], ["medical records", "care receipts"], VERIFY_IRS),
    _rule("US-2026-federal-disaster-loss", "US", 2026, "income",
          "Federal disaster loss deduction (IRC §165(i)) — potentially relevant",
          "Claim federally declared disaster losses on prior year return for faster refund. Must elect within time limits. " + VERIFY_IRS,
          ["federally declared disaster", "property loss"], ["loss documentation", "FEMA declaration"], VERIFY_IRS),
    _rule("US-2026-theft-loss", "US", 2026, "income",
          "Theft loss deduction (IRC §165) — check current rules",
          "Personal theft losses deductible only in federally declared disaster areas under current law. Business theft losses still deductible. " + VERIFY_IRS,
          ["theft of property"], ["police report", "loss documentation"], VERIFY_IRS),

    # ── Estate & Gift (expanded) ───────────────────────────────────────
    _rule("US-2026-estate-planning-trust", "US", 2026, "estate",
          "Irrevocable trust estate planning — strategic opportunity",
          "Irrevocable trusts may remove assets from estate for tax purposes. Verify current rules on grantor trusts and estate inclusion. " + VERIFY_IRS,
          ["irrevocable trust", "estate planning goal"], ["trust documents"], VERIFY_IRS),
    _rule("US-2026-portability-election", "US", 2026, "estate",
          "Portability of deceased spousal exemption — potentially relevant",
          "Surviving spouse may claim deceased spouse's unused estate tax exemption. Must file estate return to elect portability. " + VERIFY_IRS,
          ["deceased spouse", "estate tax return filing requirement"], ["estate tax return", "death certificate"], VERIFY_IRS),
    _rule("US-2026-gift-splitting", "US", 2026, "estate",
          "Gift splitting between spouses — potentially relevant",
          "Married couples can split gifts to double the annual exclusion. Both spouses must consent. " + VERIFY_IRS,
          ["married couple making gift"], ["gift records", "consent statement"], VERIFY_IRS),
    _rule("US-2026-charitable-remainder-trust", "US", 2026, "estate",
          "Charitable Remainder Trust (CRT) — strategic opportunity",
          "CRT provides income stream to non-charitable beneficiaries with remainder to charity. May provide partial deduction. " + VERIFY_IRS,
          ["funding a CRT", "charitable intent"], ["CRT documents", "appraisals"], VERIFY_IRS),
    _rule("US-2026-529-rollover", "US", 2026, "education",
          "529 plan to Roth IRA rollover (SECURE 2.0) — strategic opportunity",
          "Up to $35,000 lifetime from 529 to Roth IRA if account open 15+ years. Annual Roth contribution limits apply. Verify current rules. " + VERIFY_IRS,
          ["529 plan open 15+ years", "unused education funds"], ["529 statements"], VERIFY_IRS),

    # ── Foreign Income & Credits (expanded) ────────────────────────────
    _rule("US-2026-foreign-housing-deduction", "US", 2026, "investments",
          "Foreign housing cost deduction details — potentially relevant",
          "Self-employed taxpayers abroad may deduct housing costs above base amount as business expense. Verify location-based limits. " + VERIFY_IRS,
          ["self-employed abroad", "foreign housing costs"], ["housing expense receipts"], VERIFY_IRS),
    _rule("US-2026-treaty-benefits", "US", 2026, "investments",
          "Tax treaty benefit claims — potentially relevant",
          "Claim benefits under applicable tax treaty to reduce double taxation. Must file form to claim treaty-based positions. " + VERIFY_IRS,
          ["foreign income", "applicable tax treaty"], ["Form 8833"], VERIFY_IRS),
    _rule("US-2026-gilti-tax", "US", 2026, "business",
          "GILTI inclusion (IRC §951A) — compliance awareness",
          "Global Intangible Low-Taxed Income requires US shareholders of CFCs to include certain income annually. Verify applicability. " + VERIFY_IRS,
          ["CFC ownership", "foreign corporate income"], ["Form 8992"], VERIFY_IRS),
    _rule("US-2026-subpart-f-income", "US", 2026, "business",
          "Subpart F income inclusion — compliance awareness",
          "US shareholders must include certain passive foreign income from CFCs regardless of distribution. Verify current rules. " + VERIFY_IRS,
          ["CFC ownership"], ["Form 5471"], VERIFY_IRS),

    # ── Capital Gains & Investment (expanded) ──────────────────────────
    _rule("US-2026-1244-stock-loss", "US", 2026, "investments",
          "Section 1244 small business stock loss — potentially relevant",
          "Loss on qualifying small business stock treated as ordinary loss (up to $50K/$100K) rather than capital loss. " + VERIFY_IRS,
          ["small business stock sale at loss"], ["stock purchase records"], VERIFY_IRS),
    _rule("US-2026-abandoned-stock", "US", 2026, "investments",
          "Abandoned stock deduction (IRC §165) — potentially relevant",
          "Abandonment of worthless stock treated as sale for $0, creating capital loss. Must be truly abandoned, not sold. " + VERIFY_IRS,
          ["worthless stock"], ["abandonment documentation"], VERIFY_IRS),
    _rule("US-2026-schedule-d-worksheet", "US", 2026, "investments",
          "Schedule D tax calculation worksheet — compliance awareness",
          "Use qualified dividends and capital gain tax worksheet when you have Schedule D gains. Determines correct tax rate. " + VERIFY_IRS,
          ["capital gains or losses"], ["Schedule D", "Form 1040"], VERIFY_IRS),
    _rule("US-2026-unrecaptured-1250", "US", 2026, "investments",
          "Unrecaptured Section 1250 gain — compliance awareness",
          "Depreciation recapture on real property taxed at max 25% rate. Applies to gain from sale of depreciable real estate. " + VERIFY_IRS,
          ["sale of depreciable real property"], ["depreciation records", "Schedule D"], VERIFY_IRS),
    _rule("US-2026-passive-activity-rules", "US", 2026, "investments",
          "Passive activity rules for investors — compliance awareness",
          "Portfolio income (dividends, interest) is not passive. Activity grouping elections affect loss deductions. " + VERIFY_IRS,
          ["investment income and losses"], ["Schedule E", "Form 8582"], VERIFY_IRS),

    # ── Self-Employment & Business (expanded) ──────────────────────────
    _rule("US-2026-schedule-c-overview", "US", 2026, "business",
          "Schedule C overview for sole proprietors — compliance awareness",
          "Sole proprietors report business income and expenses on Schedule C. Net income subject to self-employment tax. " + VERIFY_IRS,
          ["sole proprietorship income"], ["Schedule C", "receipts"], VERIFY_IRS),
    _rule("US-2026-business-meal-deduction", "US", 2026, "business",
          "Business meal deduction (IRC §274) — potentially relevant",
          "Business meals are 50% deductible (temporary 100% for restaurant meals may apply). Must be directly related to business. " + VERIFY_IRS,
          ["business meal expense"], ["receipts with business purpose"], VERIFY_IRS),
    _rule("US-2026-travel-expenses", "US", 2026, "business",
          "Business travel expense deduction — potentially relevant",
          "Ordinary and necessary travel expenses for business away from home are deductible. Includes lodging, transportation, meals (50%). " + VERIFY_IRS,
          ["business travel away from home"], ["travel receipts", "expense records"], VERIFY_IRS),
    _rule("US-2026-cell-phone-deduction", "US", 2026, "business",
          "Cell phone and internet deduction — potentially relevant",
          "Business use percentage of cell phone and internet costs deductible for self-employed. Must document business use. " + VERIFY_IRS,
          ["self-employed", "business use of phone/internet"], ["bills", "usage logs"], VERIFY_IRS),
    _rule("US-2026-1099-NEC-reporting", "US", 2026, "business",
          "1099-NEC filing requirements — compliance awareness",
          "File 1099-NEC for non-employee compensation of $600+. Due to recipients by Jan 31, IRS by Feb 28 (electronic). " + VERIFY_IRS,
          ["paid $600+ to non-employee"], ["vendor W-9s", "payment records"], VERIFY_IRS),
    _rule("US-2026-estimated-tax-quarterly", "US", 2026, "compliance",
          "Estimated tax quarterly due dates — compliance awareness",
          "Q1: Apr 15, Q2: Jun 15, Q3: Sep 15, Q4: Jan 15 of following year. Missing deadlines triggers underpayment penalty. " + VERIFY_IRS,
          ["self-employment or investment income"], ["1040-ES"], VERIFY_IRS),
    _rule("US-2026-business-entity-selection", "US", 2026, "business",
          "Business entity selection and tax implications — potentially relevant",
          "Sole prop, LLC, S-Corp, C-Corp each have different tax implications. Verify which entity best suits your situation. " + VERIFY_IRS,
          ["starting or restructuring business"], ["business plan"], VERIFY_IRS),

    # ── Family & Credits (expanded) ────────────────────────────────────
    _rule("US-2026-child-tax-credit-phaseout", "US", 2026, "family",
          "Child Tax Credit phaseout thresholds — compliance awareness",
          "Credit phases out at $400K MFJ/$200K other filing statuses. Verify current thresholds and partial credit rules. " + VERIFY_IRS,
          ["qualifying child", "income near phaseout"], ["income records"], VERIFY_IRS),
    _rule("US-2026-dependency-exemption-detail", "US", 2026, "family",
          "Dependency exemption qualification rules — compliance awareness",
          "Qualifying child or qualifying relative tests must be met. Age, residency, support, and relationship tests apply. " + VERIFY_IRS,
          ["potential dependent"], ["support records", "residency documentation"], VERIFY_IRS),
    _rule("US-2026-credit-for-other-dependents", "US", 2026, "family",
          "Credit for Other Dependents (IRC §24(h)) — potentially relevant",
          "Up to $500 credit for dependents who do not qualify for Child Tax Credit. Verify eligibility requirements. " + VERIFY_IRS,
          ["qualifying dependent not under 17"], ["dependent records"], VERIFY_IRS),
    _rule("US-2026- Adoption-credit-refundable", "US", 2026, "family",
          "Adoption Credit refundable portion — potentially relevant",
          "Portion of adoption credit may be refundable for qualified domestic adoptions. Verify current refundable amount and rules. " + VERIFY_IRS,
          ["qualified domestic adoption"], ["adoption records"], VERIFY_IRS),
    _rule("US-2026-family-credit-coordination", "US", 2026, "family",
          "Family credit coordination rules — compliance awareness",
          "Multiple family credits may interact. Cannot double-claim same expenses for different credits. Coordinate across Form 2441, 8839, 8812. " + VERIFY_IRS,
          ["multiple family credits"], ["relevant credit forms"], VERIFY_IRS),

    # ── Housing & Property (expanded) ──────────────────────────────────
    _rule("US-2026-rental-income-reporting", "US", 2026, "business",
          "Rental income reporting on Schedule E — compliance awareness",
          "Report rental income and deduct rental expenses on Schedule E. Net rental income or loss flows to Form 1040. " + VERIFY_IRS,
          ["rental property income"], ["Schedule E", "rental records"], VERIFY_IRS),
    _rule("US-2026-rental-depreciation", "US", 2026, "business",
          "Rental property depreciation rules — potentially relevant",
          "Residential rental property depreciated over 27.5 years. Nonresidential over 39 years. Mid-month convention applies. " + VERIFY_IRS,
          ["rental property"], ["purchase closing statement", "depreciation schedule"], VERIFY_IRS),
    _rule("US-2026-rental-active-participation", "US", 2026, "business",
          "Rental active participation $25K exception — potentially relevant",
          "Active participants in rental real estate may deduct up to $25K of losses against non-passive income. Phases out at $100K-$150K AGI. " + VERIFY_IRS,
          ["rental real estate activity", "active participation"], ["rental records"], VERIFY_IRS),
    _rule("US-2026-home-equity-loan", "US", 2026, "housing",
          "Home equity loan interest deduction — check current rules",
          "Home equity loan interest deductible only if used to buy, build, or substantially improve the home securing the loan. " + VERIFY_IRS,
          ["home equity loan"], ["Form 1098", "loan proceeds documentation"], VERIFY_IRS),
    _rule("US-2026-property-tax-deduction", "US", 2026, "housing",
          "Property tax deduction details — potentially relevant",
          "Real property taxes deductible on Schedule A subject to $10K SALT cap. Verify current treatment of personal property taxes. " + VERIFY_IRS,
          ["real property ownership"], ["property tax bills"], VERIFY_IRS),

    # ── Retirement Advanced (expanded) ─────────────────────────────────
    _rule("US-2026-529-to-ira-rollover", "US", 2026, "retirement",
          "529 to IRA limited rollover (SECURE 2.0) — strategic opportunity",
          "Limited annual rollovers from 529 to Roth IRA, subject to contribution limits and account age requirements. Verify current rules. " + VERIFY_IRS,
          ["529 plan with excess funds"], ["529 distribution statements"], VERIFY_IRS),
    _rule("US-2026-conduit-ira", "US", 2026, "retirement",
          "Conduit IRA for 401(k) rollovers — potentially relevant",
          "Roll 401(k) to Traditional IRA to preserve tax-deferred status. 60-day rollover window. Direct trustee-to-trustee transfer preferred. " + VERIFY_IRS,
          ["401(k) rollover to IRA"], ["distribution records"], VERIFY_IRS),
    _rule("US-2026-nuance-roth-ira", "US", 2026, "retirement",
          "Non-deductible IRA basis tracking — compliance awareness",
          "Track after-tax contributions to Traditional IRA (Form 8606). Basis affects taxation of future distributions and Roth conversions. " + VERIFY_IRS,
          ["non-deductible IRA contributions"], ["Form 8606"], VERIFY_IRS),
    _rule("US-2026-roth-ira-distribution-rules", "US", 2026, "retirement",
          "Roth IRA qualified distribution rules — compliance awareness",
          "Qualified distributions from Roth IRA are tax-free. Must meet 5-year holding and age 59½ requirements. Verify ordering rules. " + VERIFY_IRS,
          ["Roth IRA distributions"], ["Form 1099-R", "Form 5498"], VERIFY_IRS),
    _rule("US-2026-saver-credit-detail", "US", 2026, "retirement",
          "Saver's Credit detailed eligibility (IRC §25B) — potentially relevant",
          "Credit up to 50% of retirement contributions (max $1,000/$2,000). Must be 18+, not a student, not a dependent. Income limits apply. " + VERIFY_IRS,
          ["retirement contribution", "income below threshold"], ["contribution records"], VERIFY_IRS),

    # ── Income Adjustments (expanded) ──────────────────────────────────
    _rule("US-2026-ira-deduction-phaseout", "US", 2026, "retirement",
          "Traditional IRA deduction phaseout (if covered by workplace plan) — compliance awareness",
          "If covered by employer plan, IRA deduction phases out at certain income levels. Higher phaseout for MFJ if spouse not covered. " + VERIFY_IRS,
          ["IRA contribution", "workplace plan coverage"], ["Form 5498", "W-2"], VERIFY_IRS),
    _rule("US-2026-hsa-deduction-limit", "US", 2026, "health",
          "HSA deduction limit coordination — compliance awareness",
          "HSA contribution deduction is subject to annual limits and proration if not HSA-eligible all 12 months. " + VERIFY_IRS,
          ["HSA contribution", "partial-year HDHP coverage"], ["Form 5498-SA"], VERIFY_IRS),
    _rule("US-2026-student-loan-interest-magi", "US", 2026, "education",
          "Student loan interest MAGI phaseout detail — potentially relevant",
          "Deduction phases out completely above certain MAGI thresholds. Verify current ranges for Single and MFJ. " + VERIFY_IRS,
          ["student loan interest paid"], ["Form 1098-E"], VERIFY_IRS),
    _rule("US-2026-educator-expense-detail", "US", 2026, "education",
          "Educator expense deduction detail (IRC §62(c)) — potentially relevant",
          "Deduction for unreimbursed expenses of K-12 teachers. Verify current dollar limit and eligible expense types. " + VERIFY_IRS,
          ["K-12 teacher or instructor"], ["expense receipts"], VERIFY_IRS),
    _rule("US-2026-alimony-post-2018", "US", 2026, "family",
          "Post-2018 alimony treatment detail — compliance awareness",
          "Alimony from divorce agreements executed after 2018 is neither deductible by payer nor includable by recipient. Verify agreement date. " + VERIFY_IRS,
          ["post-2018 divorce agreement"], ["divorce decree"], VERIFY_IRS),

    # ── Filing & Compliance (expanded) ─────────────────────────────────
    _rule("US-2026-joint-return-risks", "US", 2026, "compliance",
          "Joint return joint and several liability — compliance awareness",
          "Joint filers are jointly and separately liable for all tax on the return. Consider injured or innocent spouse relief. " + VERIFY_IRS,
          ["married filing jointly"], [], VERIFY_IRS),
    _rule("US-2026-filing-status-confirmation", "US", 2026, "filing",
          "Filing status determination — compliance awareness",
          "Correct filing status affects standard deduction, tax brackets, and eligibility for credits. Verify your qualifying status. " + VERIFY_IRS,
          ["filing status determination"], [], VERIFY_IRS),
    _rule("US-2026-withholding-accuracy", "US", 2026, "compliance",
          "Withholding accuracy and W-4 review — compliance awareness",
          "Review W-4 withholding annually to avoid underpayment or overpayment. Life events may require mid-year adjustment. " + VERIFY_IRS,
          ["W-4 withholding", "life changes"], ["W-4 form"], VERIFY_IRS),
    _rule("US-2026-state-filing-obligation", "US", 2026, "filing",
          "State income tax filing obligations — compliance awareness",
          "Federal and state returns are separate. Verify state filing requirements based on residency and income source. " + VERIFY_IRS,
          ["state income", "residency"], [], VERIFY_IRS),
    _rule("US-2026-estimated-tax-penalty-avoidance", "US", 2026, "compliance",
          "Estimated tax penalty avoidance strategies — potentially relevant",
          "Strategies to minimize underpayment penalties include annualized income installment method and safe harbor elections. " + VERIFY_IRS,
          ["variable income", "seasonal income"], ["income records", "Form 2210"], VERIFY_IRS),

    # ── Special Situations (expanded) ──────────────────────────────────
    _rule("US-2026-barter-income", "US", 2026, "income",
          "Barter income taxation — compliance awareness",
          "Fair market value of goods or services received through barter is taxable income. May require 1099-B issuance. " + VERIFY_IRS,
          ["barter transactions"], ["barter records"], VERIFY_IRS),
    _rule("US-2026-alimony-income", "US", 2026, "income",
          "Alimony as income (pre-2019 agreements) — compliance awareness",
          "Alimony received under pre-2019 agreements is taxable income to recipient. Coordinate with payer's deduction. " + VERIFY_IRS,
          ["pre-2019 alimony received"], ["alimony records"], VERIFY_IRS),
    _rule("US-2026-settlement-income", "US", 2026, "income",
          "Legal settlement income taxation — compliance awareness",
          "Tax treatment of legal settlements depends on the nature of the claim. Physical injury settlements are generally excludable. " + VERIFY_IRS,
          ["legal settlement received"], ["settlement agreement"], VERIFY_IRS),
    _rule("US-2026-gambling-income", "US", 2026, "income",
          "Gambling income and loss reporting — compliance awareness",
          "Gambling winnings are taxable income. Losses deductible only to extent of winnings, and only if itemizing. " + VERIFY_IRS,
          ["gambling winnings"], ["W-2G", "gambling records"], VERIFY_IRS),
    _rule("US-2026-prize-competition", "US", 2026, "income",
          "Prize and competition income taxation — compliance awareness",
          "Cash prizes and fair market value of non-cash prizes are taxable. Professional competition winnings taxed as ordinary income. " + VERIFY_IRS,
          ["competition or contest winnings"], ["prize records"], VERIFY_IRS),
    _rule("US-2026-royalty-income", "US", 2026, "income",
          "Royalty income taxation — potentially relevant",
          "Royalties from intellectual property, natural resources, or patents are taxable. May qualify for capital gains treatment. " + VERIFY_IRS,
          ["royalty income"], ["Form 1099-MISC", "1099-S"], VERIFY_IRS),
    _rule("US-2026-rental-vehicle-expenses", "US", 2026, "business",
          "Rental vehicle expense allocation — potentially relevant",
          "Vehicle used for rental property management may have deductible expenses. Must allocate personal vs business use. " + VERIFY_IRS,
          ["rental property vehicle use"], ["mileage logs", "expense records"], VERIFY_IRS),
    _rule("US-2026-safe-deposit-box", "US", 2026, "investments",
          "Safe deposit box rental as investment expense — compliance awareness",
          "Safe deposit box fees for storing investment documents are deductible as investment expenses if itemizing. " + VERIFY_IRS,
          ["investment-related safe deposit box"], ["rental receipts"], VERIFY_IRS),
    _rule("US-2026-solar-energy-credit-detail", "US", 2026, "energy",
          "Residential solar credit details (IRC §25D) — potentially relevant",
          "30% credit for solar installation costs including labor, panels, and battery storage. No income limit. Carryforward if exceeds tax liability. " + VERIFY_IRS,
          ["solar panel installation"], ["installation invoice", "manufacturer certification"], VERIFY_IRS),
    _rule("US-2026-ev-credit-transfer", "US", 2026, "energy",
          "EV credit point-of-sale transfer (IRC §30D) — potentially relevant",
          "Transfer clean vehicle credit to dealer at point of sale to reduce purchase price. Verify current transfer rules and eligibility. " + VERIFY_IRS,
          ["new qualifying EV purchase"], ["vehicle identification", "dealer transfer form"], VERIFY_IRS),
    _rule("US-2026-education-savings-bond", "US", 2026, "education",
          "Education savings bond interest exclusion (IRC §137) — potentially relevant",
          "Exclude interest from qualified U.S. savings bonds if used for qualified higher education expenses. Income limits apply. " + VERIFY_IRS,
          ["Series I or EE bond interest", "qualified education expenses"], ["Form 1099-INT", "Form 8815"], VERIFY_IRS),
    _rule("US-2026-unicode-deduction", "US", 2026, "compliance",
          "Uniformed services tax deduction — potentially relevant",
          "Military members may deduct unreimbursed uniform costs and travel expenses. Verify current rules for active duty. " + VERIFY_IRS,
          ["active-duty military"], ["expense receipts"], VERIFY_IRS),
    _rule("US-2026-deployment-education", "US", 2026, "education",
          "Military education benefits — potentially relevant",
          "GI Bill and Tuition Assistance benefits are generally excludable from income. Verify coordination with education credits. " + VERIFY_IRS,
          ["military education benefits"], ["benefit statements"], VERIFY_IRS),
]

BD_2026 = [
    _rule("BD-2026-investment-rebate", "BD", 2026, "retirement",
          "Investment tax rebate — potentially relevant",
          "Rebates on allowable investments (e.g. insurance premiums, DPS, savings instruments, equities) follow yearly caps and rates set in the Finance Act. Confirm the current assessment year's schedule. " + VERIFY_NBR,
          ["allowable investment", "current-year rebate schedule"], ["investment certificates", "premium receipts"], VERIFY_NBR),
    _rule("BD-2026-hra", "BD", 2026, "housing",
          "House rent allowance (salaried) — potentially relevant",
          "Salaried taxpayers may have an exempt portion of house rent allowance under yearly rules. Confirm the current exemption formula. " + VERIFY_NBR,
          ["salaried income", "actual rent paid"], ["rent receipts", "salary certificate"], VERIFY_NBR),
    _rule("BD-2026-savings-instruments", "BD", 2026, "financial",
          "Savings instruments (interest treatment) — potentially relevant",
          "Interest and encashment treatment of savings certificates and bonds follows NBR circulars that change periodically. Verify current circulars. " + VERIFY_NBR,
          ["qualifying instrument"], ["certificates", "interest statements"], VERIFY_NBR),
    _rule("BD-2026-rental-income", "BD", 2026, "housing",
          "Rental (house property) income deductions — potentially relevant",
          "Allowable deductions from rental income (repairs, municipal tax, etc.) follow yearly rules. Verify before computing. " + VERIFY_NBR,
          ["rental income declared"], ["rent deeds", "municipal tax receipts"], VERIFY_NBR),
]

PACKS: dict[tuple[str, int], list[dict]] = {
    ("GEN", 2026): GEN_2026,
    ("MX", 2026): MX_2026,
    ("US", 2026): US_2026,
    ("BD", 2026): BD_2026,
}

SUPPORTED_JURISDICTIONS = ["MX", "US", "BD"]


def rules_for(jurisdiction: str, tax_year: int = 2026) -> list[dict]:
    """Jurisdiction pack + generic fallback. Unknown countries get GEN only."""
    juris = (jurisdiction or "").upper()
    out = list(PACKS.get(("GEN", tax_year), []))
    if juris in SUPPORTED_JURISDICTIONS:
        out = list(PACKS.get((juris, tax_year), [])) + out
    return out


def normalize_country(value: str) -> str:
    v = (value or "").strip().upper()
    return v if v in SUPPORTED_JURISDICTIONS else "GEN"
