"""PDF report generation using HTML templates.

Generates professional PDF reports for portfolios, optimizations, and risk analysis.
Uses wkhtmltopdf via subprocess for HTML-to-PDF conversion, with a pure HTML fallback.
"""
import json
import logging
import os
import secrets
import subprocess
import tempfile
from datetime import datetime, timezone
from io import BytesIO
from typing import Optional

logger = logging.getLogger("quantive.pdf")


def _check_wkhtmltopdf() -> bool:
    """Check if wkhtmltopdf is available."""
    try:
        subprocess.run(["wkhtmltopdf", "--version"], capture_output=True, timeout=5)
        return True
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


HAS_WKHTMLTOPDF = _check_wkhtmltopdf()


# ── HTML Templates ──────────────────────────────────────────────────────

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1e293b; line-height: 1.5; padding: 40px; }}
    .header {{ background: linear-gradient(135deg, #1e40af, #7c3aed); color: white; padding: 30px; border-radius: 12px; margin-bottom: 30px; }}
    .header h1 {{ font-size: 24px; margin: 0 0 8px; }}
    .header .subtitle {{ opacity: 0.85; font-size: 14px; }}
    .section {{ margin-bottom: 24px; }}
    .section h2 {{ font-size: 18px; color: #1e40af; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-bottom: 16px; }}
    .metrics {{ display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 20px; }}
    .metric-card {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; min-width: 140px; flex: 1; }}
    .metric-card .label {{ font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }}
    .metric-card .value {{ font-size: 20px; font-weight: 700; color: #0f172a; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
    th {{ background: #1e40af; color: white; padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }}
    td {{ padding: 10px 12px; border-bottom: 1px solid #e2e8f0; font-size: 13px; }}
    tr:nth-child(even) {{ background: #f8fafc; }}
    .footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 11px; color: #94a3b8; }}
    .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }}
    .badge-green {{ background: #dcfce7; color: #166534; }}
    .badge-yellow {{ background: #fef9c3; color: #854d0e; }}
    .badge-red {{ background: #fee2e2; color: #991b1b; }}
    .badge-blue {{ background: #dbeafe; color: #1e40af; }}
</style>
</head>
<body>
{content}
<div class="footer">
    <p>Generated by Quantive — Government Financial Optimization Infrastructure</p>
    <p>{generated_at} | Report ID: {report_id}</p>
</div>
</body>
</html>"""


# ── Report Generators ───────────────────────────────────────────────────

def generate_portfolio_report(
    portfolio: dict,
    instruments: list[dict],
    analytics: Optional[dict] = None,
) -> str:
    """Generate HTML content for a portfolio report."""
    total_principal = sum(i.get("principal_outstanding", 0) for i in instruments)
    currency_breakdown = {}
    for inst in instruments:
        ccy = inst.get("currency", "USD")
        currency_breakdown[ccy] = currency_breakdown.get(ccy, 0) + inst.get("principal_outstanding", 0)

    instrument_rows = ""
    for inst in sorted(instruments, key=lambda x: x.get("principal_outstanding", 0), reverse=True):
        instrument_rows += f"""
        <tr>
            <td>{inst.get('name', '')}</td>
            <td>{inst.get('instrument_type', '')}</td>
            <td>{inst.get('currency', '')}</td>
            <td style="text-align:right">${inst.get('principal_outstanding', 0):,.0f}</td>
            <td style="text-align:right">{inst.get('coupon_rate', 0):.2%}</td>
            <td>{inst.get('maturity_date', '')}</td>
            <td>{inst.get('spread_bps', 0)} bps</td>
        </tr>"""

    ccy_rows = ""
    for ccy, total in sorted(currency_breakdown.items(), key=lambda x: x[1], reverse=True):
        pct = total / total_principal * 100 if total_principal > 0 else 0
        ccy_rows += f"""
        <tr>
            <td>{ccy}</td>
            <td style="text-align:right">${total:,.0f}</td>
            <td style="text-align:right">{pct:.1f}%</td>
        </tr>"""

    analytics_section = ""
    if analytics:
        dur = analytics.get("portfolio_duration", {})
        analytics_section = f"""
        <div class="section">
            <h2>Portfolio Analytics</h2>
            <div class="metrics">
                <div class="metric-card">
                    <div class="label">Macaulay Duration</div>
                    <div class="value">{dur.get('macaulay', 0):.2f} yrs</div>
                </div>
                <div class="metric-card">
                    <div class="label">Modified Duration</div>
                    <div class="value">{dur.get('modified', 0):.2f} yrs</div>
                </div>
                <div class="metric-card">
                    <div class="label">Convexity</div>
                    <div class="value">{analytics.get('convexity', 0):.2f}</div>
                </div>
            </div>
        </div>"""

    content = f"""
    <div class="header">
        <h1>Portfolio Report</h1>
        <div class="subtitle">{portfolio.get('name', 'Untitled Portfolio')}</div>
    </div>

    <div class="metrics">
        <div class="metric-card">
            <div class="label">Total Instruments</div>
            <div class="value">{len(instruments)}</div>
        </div>
        <div class="metric-card">
            <div class="label">Total Principal</div>
            <div class="value">${total_principal:,.0f}</div>
        </div>
        <div class="metric-card">
            <div class="label">Currencies</div>
            <div class="value">{len(currency_breakdown)}</div>
        </div>
    </div>

    {analytics_section}

    <div class="section">
        <h2>Instruments</h2>
        <table>
            <thead>
                <tr><th>Name</th><th>Type</th><th>Currency</th><th>Principal</th><th>Coupon</th><th>Maturity</th><th>Spread</th></tr>
            </thead>
            <tbody>{instrument_rows}</tbody>
        </table>
    </div>

    <div class="section">
        <h2>Currency Breakdown</h2>
        <table>
            <thead><tr><th>Currency</th><th>Total Principal</th><th>% of Portfolio</th></tr></thead>
            <tbody>{ccy_rows}</tbody>
        </table>
    </div>
    """
    return content


def generate_optimization_report(
    job: dict,
    strategies: list[dict],
    benchmarks: list[dict],
) -> str:
    """Generate HTML content for an optimization report."""
    strategy_rows = ""
    for s in strategies:
        metrics = s.get("metrics", {})
        feasible_badge = '<span class="badge badge-green">Feasible</span>' if s.get("feasible", True) else '<span class="badge badge-red">Infeasible</span>'
        strategy_rows += f"""
        <tr>
            <td>#{s.get('rank', 0)}</td>
            <td>{s.get('name', '')}</td>
            <td style="text-align:right">${metrics.get('expected_cost', 0):,.0f}</td>
            <td style="text-align:right">{metrics.get('refinancing_risk', 0):.1%}</td>
            <td style="text-align:right">{metrics.get('interest_rate_risk', 0):.1%}</td>
            <td>{feasible_badge}</td>
        </tr>"""

    bench_rows = ""
    for b in benchmarks:
        feasible_badge = '<span class="badge badge-green">Yes</span>' if b.get("feasible") else '<span class="badge badge-red">No</span>'
        bench_rows += f"""
        <tr>
            <td>{b.get('solver_name', '')}</td>
            <td>{feasible_badge}</td>
            <td style="text-align:right">${b.get('objective_value', 0):,.0f}</td>
            <td style="text-align:right">{b.get('execution_time_seconds', 0):.1f}s</td>
        </tr>"""

    best = strategies[0] if strategies else {}
    best_cost = best.get("metrics", {}).get("expected_cost", 0)

    content = f"""
    <div class="header">
        <h1>Optimization Report</h1>
        <div class="subtitle">{job.get('name', 'Optimization')}</div>
    </div>

    <div class="metrics">
        <div class="metric-card">
            <div class="label">Status</div>
            <div class="value"><span class="badge badge-green">{job.get('status', 'completed')}</span></div>
        </div>
        <div class="metric-card">
            <div class="label">Strategies</div>
            <div class="value">{len(strategies)}</div>
        </div>
        <div class="metric-card">
            <div class="label">Best Cost</div>
            <div class="value">${best_cost:,.0f}</div>
        </div>
        <div class="metric-card">
            <div class="label">Scenarios Tested</div>
            <div class="value">{job.get('scenario_count', '1,000')}</div>
        </div>
    </div>

    <div class="section">
        <h2>Ranked Strategies</h2>
        <table>
            <thead>
                <tr><th>Rank</th><th>Name</th><th>Expected Cost</th><th>Refinancing Risk</th><th>Rate Risk</th><th>Status</th></tr>
            </thead>
            <tbody>{strategy_rows}</tbody>
        </table>
    </div>

    <div class="section">
        <h2>Algorithm Benchmarks</h2>
        <table>
            <thead><tr><th>Solver</th><th>Feasible</th><th>Objective Value</th><th>Runtime</th></tr></thead>
            <tbody>{bench_rows}</tbody>
        </table>
    </div>
    """
    return content


def generate_risk_report(
    portfolio_name: str,
    risk_summary: dict,
) -> str:
    """Generate HTML content for a risk report."""
    risk_score = risk_summary.get("risk_score", {})
    score = risk_score.get("score", 0)
    label = risk_score.get("label", "Unknown")
    score_color = "#059669" if score <= 3 else "#f59e0b" if score <= 6 else "#dc2626"

    scenario_rows = ""
    for sc in risk_summary.get("investment_scenarios", []):
        scenario_rows += f"""
        <tr>
            <td>{sc.get('scenario_name', '')}</td>
            <td style="text-align:right">${sc.get('investment', 0):,.0f}</td>
            <td style="text-align:right">${sc.get('return_amount', 0):,.0f}</td>
            <td style="text-align:right">{sc.get('return_pct', 0):.1f}%</td>
            <td style="text-align:right">{sc.get('probability', 0):.1%}</td>
        </tr>"""

    var_rows = ""
    for v in risk_summary.get("var_analysis", []):
        var_rows += f"""
        <tr>
            <td>{v.get('confidence', 0) * 100:.0f}%</td>
            <td>{v.get('horizon_days', 0)} days</td>
            <td style="text-align:right">${v.get('var_amount', 0):,.0f}</td>
            <td style="text-align:right">{v.get('var_pct', 0):.2%}</td>
            <td style="text-align:right">${v.get('cvar_amount', 0):,.0f}</td>
        </tr>"""

    component_rows = ""
    for key, val in risk_score.get("components", {}).items():
        component_rows += f"""
        <tr>
            <td>{key.replace('_', ' ').title()}</td>
            <td style="text-align:right">{val.get('score', 0):.1f}</td>
            <td style="text-align:right">{val.get('weight', 0):.0%}</td>
            <td>{val.get('description', '')}</td>
        </tr>"""

    content = f"""
    <div class="header">
        <h1>Risk Report</h1>
        <div class="subtitle">{portfolio_name}</div>
    </div>

    <div class="metrics">
        <div class="metric-card">
            <div class="label">Risk Score</div>
            <div class="value" style="color: {score_color}">{score:.1f}/10</div>
        </div>
        <div class="metric-card">
            <div class="label">Risk Level</div>
            <div class="value">{label}</div>
        </div>
        <div class="metric-card">
            <div class="label">VaR (95%)</div>
            <div class="value">${risk_summary.get('var_analysis', [{}])[0].get('var_amount', 0) if risk_summary.get('var_analysis') else 0:,.0f}</div>
        </div>
    </div>

    <div class="section">
        <h2>Risk Components</h2>
        <table>
            <thead><tr><th>Component</th><th>Score</th><th>Weight</th><th>Description</th></tr></thead>
            <tbody>{component_rows}</tbody>
        </table>
    </div>

    <div class="section">
        <h2>Investment Scenarios</h2>
        <table>
            <thead><tr><th>Scenario</th><th>Investment</th><th>Return</th><th>Return %</th><th>Probability</th></tr></thead>
            <tbody>{scenario_rows}</tbody>
        </table>
    </div>

    <div class="section">
        <h2>VaR Analysis</h2>
        <table>
            <thead><tr><th>Confidence</th><th>Horizon</th><th>VaR Amount</th><th>VaR %</th><th>CVaR</th></tr></thead>
            <tbody>{var_rows}</tbody>
        </table>
    </div>
    """
    return content


# ── PDF Rendering ───────────────────────────────────────────────────────

def render_to_pdf(html_content: str, title: str = "Quantive Report") -> bytes:
    """Render HTML to PDF.

    Uses wkhtmltopdf if available, otherwise returns HTML as bytes.
    """
    full_html = HTML_TEMPLATE.format(
        content=html_content,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        report_id=secrets.token_hex(8),
    )

    if HAS_WKHTMLTOPDF:
        with tempfile.NamedTemporaryFile(suffix=".html", mode="w", delete=False, encoding="utf-8") as f:
            f.write(full_html)
            html_path = f.name

        pdf_path = html_path.replace(".html", ".pdf")

        try:
            result = subprocess.run(
                [
                    "wkhtmltopdf",
                    "--quiet",
                    "--page-size", "A4",
                    "--margin-top", "15mm",
                    "--margin-bottom", "15mm",
                    "--margin-left", "15mm",
                    "--margin-right", "15mm",
                    "--title", title[:200] if not title.startswith("--") else "Report",
                    html_path,
                    pdf_path,
                ],
                capture_output=True,
                timeout=30,
            )

            if result.returncode == 0 and os.path.exists(pdf_path):
                with open(pdf_path, "rb") as f:
                    pdf_bytes = f.read()
                return pdf_bytes
            else:
                logger.warning(f"wkhtmltopdf failed: {result.stderr.decode()[:500]}")
        except (subprocess.TimeoutExpired, Exception) as e:
            logger.warning(f"PDF generation error: {e}")
        finally:
            try:
                os.unlink(html_path)
                if os.path.exists(pdf_path):
                    os.unlink(pdf_path)
            except OSError:
                pass

    # Fallback: return HTML (browser can print to PDF)
    logger.info("wkhtmltopdf not available, returning HTML for browser PDF generation")
    return full_html.encode("utf-8")


def generate_portfolio_pdf(portfolio: dict, instruments: list[dict], analytics: Optional[dict] = None) -> bytes:
    """Generate a complete portfolio PDF report."""
    html = generate_portfolio_report(portfolio, instruments, analytics)
    return render_to_pdf(html, f"Portfolio Report — {portfolio.get('name', 'Untitled')}")


def generate_optimization_pdf(job: dict, strategies: list[dict], benchmarks: list[dict]) -> bytes:
    """Generate a complete optimization PDF report."""
    html = generate_optimization_report(job, strategies, benchmarks)
    return render_to_pdf(html, f"Optimization Report — {job.get('name', 'Optimization')}")


def generate_risk_pdf(portfolio_name: str, risk_summary: dict) -> bytes:
    """Generate a complete risk report PDF."""
    html = generate_risk_report(portfolio_name, risk_summary)
    return render_to_pdf(html, f"Risk Report — {portfolio_name}")


# ── API Helpers ─────────────────────────────────────────────────────────

def get_pdf_content_type(data: bytes) -> str:
    """Determine if output is PDF or HTML."""
    if data[:5] == b"%PDF-":
        return "application/pdf"
    return "text/html"


def get_pdf_extension(data: bytes) -> str:
    """Get file extension based on content."""
    return ".pdf" if data[:5] == b"%PDF-" else ".html"
