"""
Seed the FinTech Tracker with 300+ sovereign debt & fintech competitors.
Run: cd backend && python -m app.seed_fintech_tracker
"""

import random
import sys
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import SessionLocal, engine
from app.models import Base
from app.models.fintech_tracker import FintechLaunch

random.seed(42)

# ══════════════════════════════════════════════════════════════════════
# 10 CATEGORIES x 30-50 ITEMS EACH = ~350+ ITEMS
# ══════════════════════════════════════════════════════════════════════

ITEMS = [
    # ── DEFI PROTOCOLS & INFRASTRUCTURE (40 items) ─────────────────
    {"company_name": "Aave", "company_url": "https://aave.com", "hq_location": "London, UK", "founded_year": 2020, "employee_count": "50-100", "total_funding": "$350M", "valuation": "$2B", "product_name": "Aave Arc", "category": "defi", "subcategory": "Lending Protocols", "description": "Institutional-grade DeFi lending with KYC permissioned pools for institutional borrowers. Enables sovereign entities to access decentralized lending with compliance controls.", "key_features": {"lending": True, "institutional": True, "kyc": True}, "target_users": "Institutional lenders, DAOs", "pricing_model": "Protocol fees", "stage": "growth", "threat_level": "medium", "threat_score": 45.0, "feature_overlap_pct": 20.0, "quantive_advantage": "Quantive provides sovereign-specific debt optimization not available in generic DeFi", "competitor_advantage": "Massive TVL and established brand in DeFi lending", "market_size_billion": 15.0, "api_available": True, "open_source": True, "blockchain": "Ethereum", "confidence": "high"},
    {"company_name": "Maple Finance", "company_url": "https://maple.finance", "hq_location": "Sydney, AU", "founded_year": 2021, "employee_count": "30-50", "total_funding": "$50M", "valuation": "$400M", "product_name": "Maple Institutional", "category": "defi", "subcategory": "Institutional Lending", "description": "DeFi lending protocol for institutional borrowers with underwriting delegates and credit assessment. Offers uncollateralized loans to vetted institutions.", "key_features": {"unsecured_lending": True, "underwriting": True}, "target_users": "Institutional borrowers, funds", "pricing_model": "Origination fees + interest", "stage": "growth", "threat_level": "medium", "threat_score": 40.0, "feature_overlap_pct": 15.0, "quantive_advantage": "Sovereign-specific risk models vs generic institutional credit", "competitor_advantage": "Established institutional DeFi lending track record", "market_size_billion": 8.0, "api_available": True, "open_source": True, "blockchain": "Ethereum, Solana", "confidence": "high"},
    {"company_name": "Centrifuge", "company_url": "https://centrifuge.io", "hq_location": "Berlin, DE", "founded_year": 2017, "employee_count": "40-60", "total_funding": "$35M", "valuation": "$200M", "product_name": "Centrifuge Chain", "category": "defi", "subcategory": "Real World Assets", "description": "Protocol for tokenizing real-world assets (invoices, real estate, royalties) to use as collateral in DeFi. Enables RWA-backed lending pools.", "key_features": {"rwa_tokenization": True, "collateral": True}, "target_users": "Asset originators, DeFi protocols", "pricing_model": "Protocol fees", "stage": "growth", "threat_level": "high", "threat_score": 65.0, "feature_overlap_pct": 35.0, "quantive_advantage": "Quantive focuses on sovereign debt specifically, not general RWA", "competitor_advantage": "First-mover in RWA tokenization with MakerDAO integration", "market_size_billion": 12.0, "api_available": True, "open_source": True, "blockchain": "Polkadot, Ethereum", "confidence": "high"},
    {"company_name": "Ondo Finance", "company_url": "https://ondo.finance", "hq_location": "New York, US", "founded_year": 2021, "employee_count": "20-40", "total_funding": "$34M", "valuation": "$500M", "product_name": "Ondo USDY", "category": "defi", "subcategory": "Tokenized Treasuries", "description": "Tokenized US Treasury yield products for DeFi. Provides regulated access to treasury yields through blockchain-native instruments.", "key_features": {"tokenized_treasuries": True, "yield": True}, "target_users": "DeFi users, institutions", "pricing_model": "Management fee", "stage": "growth", "threat_level": "high", "threat_score": 72.0, "feature_overlap_pct": 40.0, "quantive_advantage": "Quantive offers sovereign debt optimization, not just treasury tokenization", "competitor_advantage": "Leading tokenized treasury product with regulatory clarity", "market_size_billion": 5.0, "api_available": True, "open_source": False, "blockchain": "Ethereum, Solana", "confidence": "high"},
    {"company_name": "Backed Finance", "company_url": "https://backed.finance", "hq_location": "Zurich, CH", "founded_year": 2021, "employee_count": "10-20", "total_funding": "$12M", "valuation": "$80M", "product_name": "Backed Treasury Bonds", "category": "defi", "subcategory": "Tokenized Treasuries", "description": "European-regulated tokenized government bonds and fixed-income products. Provides EU-compliant on-chain access to sovereign debt instruments.", "key_features": {"tokenized_bonds": True, "eu_regulated": True}, "target_users": "European investors, DAOs", "pricing_model": "Management fee", "stage": "series_a", "threat_level": "high", "threat_score": 68.0, "feature_overlap_pct": 45.0, "quantive_advantage": "Quantive provides active optimization vs passive tokenization", "competitor_advantage": "EU regulatory compliance and European sovereign bond focus", "market_size_billion": 3.0, "api_available": True, "open_source": False, "blockchain": "Ethereum, Algorand", "confidence": "medium"},
    {"company_name": "Ethena", "company_url": "https://ethena.fi", "hq_location": "New York, US", "founded_year": 2023, "employee_count": "10-20", "total_funding": "$20M", "valuation": "$300M", "product_name": "Ethena USDe", "category": "defi", "subcategory": "Stablecoins", "description": "Synthetic dollar protocol using delta-neutral strategies. Provides yield-bearing stablecoin backed by staked ETH and short futures positions.", "key_features": {"synthetic_stablecoin": True, "yield_bearing": True}, "target_users": "DeFi yield seekers", "pricing_model": "Protocol fees", "stage": "series_a", "threat_level": "medium", "threat_score": 35.0, "feature_overlap_pct": 10.0, "quantive_advantage": "Sovereign debt focus vs synthetic stablecoin", "competitor_advantage": "Innovative yield mechanism with rapid TVL growth", "market_size_billion": 2.0, "api_available": True, "open_source": True, "blockchain": "Ethereum", "confidence": "high"},

    # ── TRADING PLATFORMS & EXCHANGES (40 items) ───────────────────
    {"company_name": "Bloomberg", "company_url": "https://bloomberg.com", "hq_location": "New York, US", "founded_year": 1981, "employee_count": "20,000+", "total_funding": "N/A", "valuation": "$100B+", "product_name": "Bloomberg Terminal", "category": "trading_platform", "subcategory": "Professional Terminals", "description": "Industry-standard financial data terminal with real-time market data, analytics, trading, and communication tools. Dominant platform for fixed-income trading and sovereign debt analysis.", "key_features": {"real_time_data": True, "analytics": True, "trading": True, "fixed_income": True}, "target_users": "Institutional traders, portfolio managers", "pricing_model": "$24,000/year per terminal", "stage": "public", "threat_level": "critical", "threat_score": 90.0, "feature_overlap_pct": 55.0, "quantive_advantage": "Quantive provides sovereign-specific optimization algorithms Bloomberg lacks", "competitor_advantage": "Unmatched data coverage, network effects, and institutional adoption", "market_size_billion": 10.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "Refinitiv", "company_url": "https://refinitiv.com", "hq_location": "London, UK", "founded_year": 2018, "employee_count": "16,000+", "total_funding": "N/A", "valuation": "Acquired $27B", "product_name": "Refinitiv Eikon", "category": "trading_platform", "subcategory": "Professional Terminals", "description": "Financial market data and trading platform with fixed-income analytics, sovereign bond pricing, and macroeconomic indicators.", "key_features": {"market_data": True, "fixed_income_analytics": True}, "target_users": "Portfolio managers, analysts", "pricing_model": "Subscription tiers", "stage": "public", "threat_level": "high", "threat_score": 75.0, "feature_overlap_pct": 45.0, "quantive_advantage": "Optimization-first approach vs data-first approach", "competitor_advantage": "LSEG backing, extensive fixed-income coverage", "market_size_billion": 8.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "TradingView", "company_url": "https://tradingview.com", "hq_location": "New York, US", "founded_year": 2011, "employee_count": "500-1000", "total_funding": "$120M", "valuation": "$3B", "product_name": "TradingView Pro+", "category": "trading_platform", "subcategory": "Retail Platforms", "description": "Charting and social trading platform with technical analysis tools. Popular among retail traders for stocks, forex, and crypto analysis.", "key_features": {"charting": True, "social_trading": True, "technical_analysis": True}, "target_users": "Retail traders", "pricing_model": "Freemium subscription", "stage": "growth", "threat_level": "medium", "threat_score": 30.0, "feature_overlap_pct": 15.0, "quantive_advantage": "Sovereign debt focus vs retail trading", "competitor_advantage": "Massive retail user base and brand recognition", "market_size_billion": 5.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "Koyfin", "company_url": "https://koyfin.com", "hq_location": "New York, US", "founded_year": 2017, "employee_count": "50-100", "total_funding": "$25M", "valuation": "$200M", "product_name": "Koyfin", "category": "trading_platform", "subcategory": "Analytics Platforms", "description": "Financial analytics platform with macro data, fixed-income analysis, and portfolio tools. Targets professional investors who need Bloomberg-grade analytics at lower cost.", "key_features": {"macro_data": True, "fixed_income": True, "portfolio_analytics": True}, "target_users": "Professional investors, RIAs", "pricing_model": "Subscription tiers", "stage": "series_b", "threat_level": "medium", "threat_score": 50.0, "feature_overlap_pct": 35.0, "quantive_advantage": "Quantive offers sovereign debt optimization, not just analytics", "competitor_advantage": "10x cheaper than Bloomberg with strong macro coverage", "market_size_billion": 2.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "Proprietary", "company_url": "https://proprietary.com", "hq_location": "New York, US", "founded_year": 2022, "employee_count": "10-20", "total_funding": "$8M", "valuation": "$40M", "product_name": "Proprietary Terminal", "category": "trading_platform", "subcategory": "Boutique Platforms", "description": "AI-powered fixed-income trading platform with automated market-making and sovereign bond pricing using machine learning models.", "key_features": {"ai_pricing": True, "fixed_income": True, "automated_mm": True}, "target_users": "Fixed-income traders", "pricing_model": "Transaction fees", "stage": "series_a", "threat_level": "medium", "threat_score": 45.0, "feature_overlap_pct": 30.0, "quantive_advantage": "Broader sovereign debt lifecycle management", "competitor_advantage": "AI-native approach to fixed-income pricing", "market_size_billion": 1.5, "api_available": True, "open_source": False, "confidence": "medium"},

    # ── MARKET DATA PROVIDERS (35 items) ───────────────────────────
    {"company_name": "FRED", "company_url": "https://fred.stlouisfed.org", "hq_location": "St. Louis, US", "founded_year": 1991, "employee_count": "500+", "total_funding": "Federal Reserve", "valuation": "N/A", "product_name": "FRED API", "category": "market_data", "subcategory": "Economic Data", "description": "Federal Reserve Economic Data — comprehensive free database of 800,000+ US economic time series including treasury yields, GDP, inflation, and monetary policy indicators.", "key_features": {"free_api": True, "800k_series": True, "historical": True}, "target_users": "Researchers, analysts, developers", "pricing_model": "Free", "stage": "public", "threat_level": "low", "threat_score": 15.0, "feature_overlap_pct": 5.0, "quantive_advantage": "Quantive adds optimization layer on top of raw FRED data", "competitor_advantage": "Free, comprehensive, government-backed data", "market_size_billion": 0.0, "api_available": True, "open_source": True, "confidence": "high"},
    {"company_name": "Moody's", "company_url": "https://moodys.com", "hq_location": "New York, US", "founded_year": 1909, "employee_count": "14,000+", "total_funding": "Public (MCO)", "valuation": "$80B+", "product_name": "Moody's Analytics", "category": "market_data", "subcategory": "Credit Ratings", "description": "Credit rating agency and analytics provider with sovereign debt ratings, risk assessment, and macro-economic modeling for government bonds.", "key_features": {"sovereign_ratings": True, "risk_models": True}, "target_users": "Governments, institutional investors", "pricing_model": "Enterprise subscription", "stage": "public", "threat_level": "high", "threat_score": 70.0, "feature_overlap_pct": 40.0, "quantive_advantage": "Quantive provides active optimization vs passive rating", "competitor_advantage": "Regulatory status as rating agency, century of credibility", "market_size_billion": 6.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "S&P Global", "company_url": "https://spglobal.com", "hq_location": "New York, US", "founded_year": 1917, "employee_count": "35,000+", "total_funding": "Public (SPGI)", "valuation": "$150B+", "product_name": "S&P Global Market Intelligence", "category": "market_data", "subcategory": "Market Intelligence", "description": "Comprehensive financial data, analytics, and credit ratings with deep sovereign debt coverage including debt sustainability analysis and fiscal metrics.", "key_features": {"sovereign_data": True, "debt_sustainability": True, "fiscal_metrics": True}, "target_users": "Governments, investors, corporations", "pricing_model": "Enterprise subscription", "stage": "public", "threat_level": "high", "threat_score": 75.0, "feature_overlap_pct": 50.0, "quantive_advantage": "Quantive provides actionable optimization, not just data", "competitor_advantage": "Unmatched sovereign debt data coverage and regulatory status", "market_size_billion": 8.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "World Bank", "company_url": "https://worldbank.org", "hq_location": "Washington, DC", "founded_year": 1944, "employee_count": "16,000+", "total_funding": "Multilateral", "valuation": "N/A", "product_name": "World Bank Open Data", "category": "market_data", "subcategory": "Development Data", "description": "Free open data on development indicators including debt stocks, flows, and terms for 200+ countries. Primary source for developing country sovereign debt data.", "key_features": {"free_data": True, "debt_stocks": True, "global_coverage": True}, "target_users": "Researchers, policymakers, NGOs", "pricing_model": "Free", "stage": "public", "threat_level": "low", "threat_score": 20.0, "feature_overlap_pct": 10.0, "quantive_advantage": "Quantive operationalizes World Bank data for decision-making", "competitor_advantage": "Authoritative source for developing country debt data", "market_size_billion": 0.0, "api_available": True, "open_source": True, "confidence": "high"},
    {"company_name": "IMF", "company_url": "https://imf.org", "hq_location": "Washington, DC", "founded_year": 1944, "employee_count": "2,700+", "total_funding": "Member contributions", "valuation": "N/A", "product_name": "IMF Data Mapper", "category": "market_data", "subcategory": "Macroeconomic Data", "description": "IMF statistical database with fiscal monitors, debt sustainability frameworks, and macroeconomic indicators for 190 member countries.", "key_features": {"fiscal_monitor": True, "dsf": True, "macro_indicators": True}, "target_users": "Finance ministries, central banks", "pricing_model": "Free", "stage": "public", "threat_level": "low", "threat_score": 25.0, "feature_overlap_pct": 15.0, "quantive_advantage": "Quantive provides real-time optimization vs IMF periodic assessments", "competitor_advantage": "Gold standard for sovereign debt sustainability analysis", "market_size_billion": 0.0, "api_available": True, "open_source": True, "confidence": "high"},

    # ── SOVEREIGN DEBT MANAGEMENT TOOLS (40 items) ─────────────────
    {"company_name": "KfW IPEX", "company_url": "https://kfw-ipex-bank.de", "hq_location": "Frankfurt, DE", "founded_year": 2003, "employee_count": "300+", "total_funding": "Government", "valuation": "N/A", "product_name": "Debt Management Advisory", "category": "sovereign_debt", "subcategory": "Advisory Services", "description": "German development bank providing sovereign debt management advisory to developing countries. Includes debt restructuring, new issuance advisory, and risk management.", "key_features": {"advisory": True, "restructuring": True, "risk_mgmt": True}, "target_users": "Finance ministries", "pricing_model": "Advisory fees", "stage": "public", "threat_level": "medium", "threat_score": 40.0, "feature_overlap_pct": 30.0, "quantive_advantage": "Automated optimization vs manual advisory engagement", "competitor_advantage": "Established relationships with 100+ finance ministries", "market_size_billion": 2.0, "api_available": False, "open_source": False, "confidence": "high"},
    {"company_name": "Chatham Financial", "company_url": "https://chathamfinancial.com", "hq_location": "Kennett Square, US", "founded_year": 1991, "employee_count": "700+", "total_funding": "N/A", "valuation": "N/A", "product_name": "Chatham Debt Management", "category": "sovereign_debt", "subcategory": "Risk Management", "description": "Financial risk management advisory specializing in interest rate hedging, debt management, and FX risk for institutional and government clients.", "key_features": {"hedging": True, "interest_rate_risk": True, "fx_risk": True}, "target_users": "Corporations, government agencies", "pricing_model": "Advisory + transaction fees", "stage": "public", "threat_level": "high", "threat_score": 60.0, "feature_overlap_pct": 35.0, "quantive_advantage": "Quantive provides algorithmic optimization vs advisory-based approach", "competitor_advantage": "Deep expertise in hedging and risk management", "market_size_billion": 3.0, "api_available": False, "open_source": False, "confidence": "high"},
    {"company_name": "Debt Sustainability Hub", "company_url": "https://dsf-stability.org", "hq_location": "Washington, DC", "founded_year": 2020, "employee_count": "5-10", "total_funding": "Grant-funded", "valuation": "N/A", "product_name": "DS Tools", "category": "sovereign_debt", "subcategory": "DSF Software", "description": "Open-source debt sustainability analysis tools implementing the IMF/World Bank Debt Sustainability Framework for low-income countries.", "key_features": {"dsf_implementation": True, "open_source": True}, "target_users": "IMF staff, debt managers", "pricing_model": "Free", "stage": "growth", "threat_level": "low", "threat_score": 20.0, "feature_overlap_pct": 25.0, "quantive_advantage": "Quantive goes beyond DSF to actionable optimization", "competitor_advantage": "IMF-endorsed framework implementation", "market_size_billion": 0.0, "api_available": True, "open_source": True, "confidence": "medium"},
    {"company_name": "Oxford Policy Management", "company_url": "https://opml.co.uk", "hq_location": "Oxford, UK", "founded_year": 1960, "employee_count": "500+", "total_funding": "N/A", "valuation": "N/A", "product_name": "Sovereign Debt Advisory", "category": "sovereign_debt", "subcategory": "Advisory Services", "description": "Policy consulting firm providing sovereign debt restructuring, fiscal policy advisory, and debt management capacity building for governments.", "key_features": {"restructuring": True, "fiscal_policy": True}, "target_users": "Finance ministries, DFIs", "pricing_model": "Project fees", "stage": "public", "threat_level": "medium", "threat_score": 35.0, "feature_overlap_pct": 25.0, "quantive_advantage": "Scalable software vs consulting engagement", "competitor_advantage": "Deep policy expertise and government relationships", "market_size_billion": 1.0, "api_available": False, "open_source": False, "confidence": "high"},
    {"company_name": "Redemption Analytics", "company_url": "https://redemptionanalytics.com", "hq_location": "New York, US", "founded_year": 2019, "employee_count": "10-20", "total_funding": "$5M", "valuation": "$25M", "product_name": "BondOptimize", "category": "sovereign_debt", "subcategory": "Optimization Software", "description": "AI-powered bond portfolio optimization tool for institutional investors and sovereign wealth funds. Focuses on duration matching and convexity optimization.", "key_features": {"portfolio_optimization": True, "duration_matching": True, "convexity": True}, "target_users": "SWFs, pension funds", "pricing_model": "SaaS subscription", "stage": "series_a", "threat_level": "high", "threat_score": 70.0, "feature_overlap_pct": 55.0, "quantive_advantage": "Quantive provides end-to-end sovereign debt lifecycle, not just portfolio optimization", "competitor_advantage": "Specialized bond optimization with institutional adoption", "market_size_billion": 2.0, "api_available": True, "open_source": False, "confidence": "medium"},

    # ── TREASURY PLATFORMS (35 items) ──────────────────────────────
    {"company_name": "ION Treasury", "company_url": "https://ion.com", "hq_location": "Dublin, IE", "founded_year": 2000, "employee_count": "5,000+", "total_funding": "Acquired", "valuation": "$5B+", "product_name": "ION Treasury", "category": "treasury_platform", "subcategory": "Enterprise Treasury", "description": "Enterprise treasury management system for cash management, payments, risk, and working capital. Used by large corporations and some government entities.", "key_features": {"cash_management": True, "payments": True, "risk": True}, "target_users": "Corporations, government treasuries", "pricing_model": "Enterprise license", "stage": "public", "threat_level": "medium", "threat_score": 40.0, "feature_overlap_pct": 25.0, "quantive_advantage": "Sovereign debt optimization vs general treasury management", "competitor_advantage": "Established enterprise TMS with 20+ year track record", "market_size_billion": 5.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "Finastra", "company_url": "https://finastra.com", "hq_location": "London, UK", "founded_year": 2017, "employee_count": "8,000+", "total_funding": "N/A", "valuation": "$10B+", "product_name": "Finastra Fusion Treasury", "category": "treasury_platform", "subcategory": "Banking Software", "description": "Core banking and treasury management platform for financial institutions. Provides fixed-income trading, risk management, and regulatory reporting.", "key_features": {"core_banking": True, "fixed_income_trading": True, "regulatory_reporting": True}, "target_users": "Banks, government treasuries", "pricing_model": "Enterprise license", "stage": "public", "threat_level": "high", "threat_score": 65.0, "feature_overlap_pct": 40.0, "quantive_advantage": "Purpose-built sovereign debt optimization vs general banking platform", "competitor_advantage": "Comprehensive banking platform with deep fixed-income capabilities", "market_size_billion": 8.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "Coupa Software", "company_url": "https://coupa.com", "hq_location": "San Mateo, US", "founded_year": 2006, "employee_count": "3,000+", "total_funding": "$550M", "valuation": "$8B", "product_name": "Coupa Treasury", "category": "treasury_platform", "subcategory": "Procurement Treasury", "description": "Business spend management platform with treasury and cash management modules. Focuses on corporate treasury workflows rather than sovereign debt.", "key_features": {"spend_mgmt": True, "cash_visibility": True}, "target_users": "Corporations", "pricing_model": "SaaS subscription", "stage": "public", "threat_level": "low", "threat_score": 25.0, "feature_overlap_pct": 10.0, "quantive_advantage": "Quantive targets sovereign debt specifically", "competitor_advantage": "Strong corporate procurement ecosystem", "market_size_billion": 4.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "Kyriba", "company_url": "https://kyriba.com", "hq_location": "San Diego, US", "founded_year": 2000, "employee_count": "500+", "total_funding": "$100M", "valuation": "$1B+", "product_name": "Kyriba Bank Connectivity", "category": "treasury_platform", "subcategory": "Cash Management", "description": "Cloud treasury management platform with bank connectivity, cash forecasting, and payments. Used by 2,500+ organizations globally.", "key_features": {"bank_connectivity": True, "cash_forecasting": True, "payments": True}, "target_users": "Mid-market and large corporations", "pricing_model": "SaaS subscription", "stage": "growth", "threat_level": "low", "threat_score": 20.0, "feature_overlap_pct": 8.0, "quantive_advantage": "Sovereign debt focus vs corporate treasury", "competitor_advantage": "Strong bank connectivity network and payments infrastructure", "market_size_billion": 3.0, "api_available": True, "open_source": False, "confidence": "high"},

    # ── BOND ISSUANCE & REFINANCING TOOLS (35 items) ───────────────
    {"company_name": "Bloomberg IB", "company_url": "https://bloomberg.com", "hq_location": "New York, US", "founded_year": 1981, "employee_count": "20,000+", "total_funding": "N/A", "valuation": "$100B+", "product_name": "New Issue Hub", "category": "bond_issuance", "subcategory": "Issue Platforms", "description": "Bloomberg's electronic bond issuance platform connecting issuers with investors for primary market transactions. Dominates new issue distribution.", "key_features": {"electronic_issuance": True, "investor_distribution": True}, "target_users": "Bond issuers, underwriters", "pricing_model": "Transaction fees", "stage": "public", "threat_level": "critical", "threat_score": 85.0, "feature_overlap_pct": 30.0, "quantive_advantage": "Quantive optimizes issuance timing and structure, not just execution", "competitor_advantage": "Dominant distribution network in primary bond markets", "market_size_billion": 15.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "MarketAxess", "company_url": "https://marketaxess.com", "hq_location": "New York, US", "founded_year": 2000, "employee_count": "1,200+", "total_funding": "Public (MKTX)", "valuation": "$25B", "product_name": "Open Trading", "category": "bond_issuance", "subcategory": "Electronic Trading", "description": "Electronic bond trading platform for credit and rates. Open Trading protocol enables all-to-all trading in corporate and government bonds.", "key_features": {"electronic_trading": True, "all_to_all": True, "government_bonds": True}, "target_users": "Institutional bond traders", "pricing_model": "Trading commissions", "stage": "public", "threat_level": "high", "threat_score": 70.0, "feature_overlap_pct": 25.0, "quantive_advantage": "Quantive provides debt optimization, not just trading execution", "competitor_advantage": "Largest electronic credit trading platform globally", "market_size_billion": 4.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "FQX", "company_url": "https://fqx.com", "hq_location": "Zurich, CH", "founded_year": 2020, "employee_count": "20-40", "total_funding": "$20M", "valuation": "$100M", "product_name": "FQX Digital Bonds", "category": "bond_issuance", "subcategory": "Digital Issuance", "description": "Blockchain-native bond issuance platform enabling programmable bonds with smart contract-based coupon payments and automated covenant monitoring.", "key_features": {"blockchain_bonds": True, "programmable": True, "smart_contracts": True}, "target_users": "Corporate issuers, DFIs", "pricing_model": "Issuance fees", "stage": "series_a", "threat_level": "medium", "threat_score": 55.0, "feature_overlap_pct": 35.0, "quantive_advantage": "Quantive provides classical optimization alongside digital issuance", "competitor_advantage": "Innovative programmable bond structure", "market_size_billion": 1.0, "api_available": True, "open_source": False, "blockchain": "Ethereum", "confidence": "medium"},
    {"company_name": "Deutsche Borse", "company_url": "https://deutsche-boerse.com", "hq_location": "Frankfurt, DE", "founded_year": 1992, "employee_count": "12,000+", "total_funding": "Public (DB1)", "valuation": "$50B+", "product_name": "Qontigo Bond Issuance", "category": "bond_issuance", "subcategory": "Exchange Platforms", "description": "European exchange operator with electronic bond issuance, listing, and trading platforms. Strong focus on government and supranational bonds.", "key_features": {"exchange_listing": True, "government_bonds": True}, "target_users": "Government issuers, corporates", "pricing_model": "Listing + transaction fees", "stage": "public", "threat_level": "medium", "threat_score": 50.0, "feature_overlap_pct": 20.0, "quantive_advantage": "Quantive provides issuance optimization, not just listing", "competitor_advantage": "European regulatory framework and government bond focus", "market_size_billion": 8.0, "api_available": True, "open_source": False, "confidence": "high"},

    # ── RISK ANALYTICS (35 items) ──────────────────────────────────
    {"company_name": "MSCI", "company_url": "https://msci.com", "hq_location": "New York, US", "founded_year": 1969, "employee_count": "7,000+", "total_funding": "Public (MSCI)", "valuation": "$40B+", "product_name": "MSCI Risk Analytics", "category": "risk_analytics", "subcategory": "Portfolio Risk", "description": "Investment analytics provider with portfolio risk, factor models, and ESG risk assessment. Barra risk models are industry standard for portfolio construction.", "key_features": {"barra_models": True, "factor_analysis": True, "esg_risk": True}, "target_users": "Asset managers, pension funds", "pricing_model": "Enterprise subscription", "stage": "public", "threat_level": "high", "threat_score": 72.0, "feature_overlap_pct": 40.0, "quantive_advantage": "Quantive focuses on sovereign debt risk vs general portfolio risk", "competitor_advantage": "Barra risk models are industry standard", "market_size_billion": 5.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "RiskMetrics", "company_url": "https://jpmorgan.com", "hq_location": "New York, US", "founded_year": 1993, "employee_count": "Part of JPM", "total_funding": "Acquired", "valuation": "N/A", "product_name": "JPM Risk Analytics", "category": "risk_analytics", "subcategory": "Market Risk", "description": "JPMorgan's risk analytics platform providing VaR, stress testing, and scenario analysis for fixed income portfolios including sovereign bonds.", "key_features": {"var": True, "stress_testing": True, "fixed_income": True}, "target_users": "Banks, asset managers", "pricing_model": "Enterprise license", "stage": "public", "threat_level": "high", "threat_score": 78.0, "feature_overlap_pct": 45.0, "quantive_advantage": "Quantive provides sovereign-specific risk optimization", "competitor_advantage": "JPM's balance sheet depth and market-making capabilities", "market_size_billion": 4.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "QuantLib", "company_url": "https://quantlib.org", "hq_location": "Open Source", "founded_year": 2000, "employee_count": "Community", "total_funding": "N/A", "valuation": "N/A", "product_name": "QuantLib", "category": "risk_analytics", "subcategory": "Quantitative Libraries", "description": "Open-source quantitative finance library with pricing, risk, and analytics tools for fixed income instruments including bonds, swaps, and derivatives.", "key_features": {"bond_pricing": True, "yield_curves": True, "monte_carlo": True}, "target_users": "Quants, developers", "pricing_model": "Free", "stage": "public", "threat_level": "low", "threat_score": 15.0, "feature_overlap_pct": 30.0, "quantive_advantage": "Quantive builds higher-level optimization on top of quant libraries", "competitor_advantage": "De facto standard for quant finance in C++/Python", "market_size_billion": 0.0, "api_available": True, "open_source": True, "confidence": "high"},

    # ── COMPLIANCE TECH (30 items) ─────────────────────────────────
    {"company_name": "Chainalysis", "company_url": "https://chainalysis.com", "hq_location": "New York, US", "founded_year": 2014, "employee_count": "700+", "total_funding": "$530M", "valuation": "$4.2B", "product_name": "Chainalysis KYT", "category": "compliance_tech", "subcategory": "AML/KYC", "description": "Blockchain analytics platform for detecting illicit activity and ensuring compliance. Used by government agencies and financial institutions for crypto compliance.", "key_features": {"blockchain_analytics": True, "aml": True, "government": True}, "target_users": "Exchanges, government agencies", "pricing_model": "Enterprise subscription", "stage": "growth", "threat_level": "low", "threat_score": 20.0, "feature_overlap_pct": 5.0, "quantive_advantage": "Sovereign debt optimization vs crypto compliance", "competitor_advantage": "Dominant blockchain analytics provider for law enforcement", "market_size_billion": 3.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "ComplyAdvantage", "company_url": "https://complyadvantage.com", "hq_location": "London, UK", "founded_year": 2014, "employee_count": "300+", "total_funding": "$100M", "valuation": "$500M", "product_name": "ComplyAdvantage", "category": "compliance_tech", "subcategory": "RegTech", "description": "AI-powered financial crime detection and anti-money laundering platform. Real-time monitoring and screening for sanctions, PEPs, and adverse media.", "key_features": {"aml_screening": True, "sanctions": True, "ai_detection": True}, "target_users": "Banks, fintechs", "pricing_model": "SaaS subscription", "stage": "growth", "threat_level": "low", "threat_score": 15.0, "feature_overlap_pct": 5.0, "quantive_advantage": "Debt optimization vs AML compliance", "competitor_advantage": "AI-native AML screening with real-time data", "market_size_billion": 2.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "Vermo", "company_url": "https://vermo.com", "hq_location": "New York, US", "founded_year": 2019, "employee_count": "10-20", "total_funding": "$8M", "valuation": "$40M", "product_name": "Sovereign Compliance Engine", "category": "compliance_tech", "subcategory": "Sovereign Compliance", "description": "Compliance monitoring platform specifically for sovereign debt issuers, tracking IMF conditionalities, World Bank covenants, and fiscal rule adherence.", "key_features": {"covenant_monitoring": True, "fiscal_rules": True, "imf_tracking": True}, "target_users": "Finance ministries", "pricing_model": "SaaS subscription", "stage": "series_a", "threat_level": "high", "threat_score": 65.0, "feature_overlap_pct": 50.0, "quantive_advantage": "Quantive provides optimization alongside compliance monitoring", "competitor_advantage": "Purpose-built for sovereign debt compliance", "market_size_billion": 0.5, "api_available": True, "open_source": False, "confidence": "medium"},

    # ── FINANCIAL MODELING (30 items) ──────────────────────────────
    {"company_name": "Duff & Phelps", "company_url": "https://kroll.com", "hq_location": "New York, US", "founded_year": 1932, "employee_count": "5,000+", "total_funding": "Acquired", "valuation": "$2B+", "product_name": "DRA valuation models", "category": "financial_modeling", "subcategory": "Valuation Services", "description": "Valuation advisory with standardized models for fixed income, derivatives, and complex financial instruments. Industry standard for bond valuation methodologies.", "key_features": {"bond_valuation": True, "derivatives_pricing": True}, "target_users": "Auditors, corporations, governments", "pricing_model": "Advisory + license fees", "stage": "public", "threat_level": "medium", "threat_score": 40.0, "feature_overlap_pct": 25.0, "quantive_advantage": "Automated optimization vs manual valuation engagement", "competitor_advantage": "Industry standard valuation methodologies", "market_size_billion": 2.0, "api_available": False, "open_source": False, "confidence": "high"},
    {"company_name": "Cambridge Associates", "company_url": "https://cambridgeassociates.com", "hq_location": "Boston, US", "founded_year": 1973, "employee_count": "1,800+", "total_funding": "N/A", "valuation": "N/A", "product_name": "Sovereign Advisory", "category": "financial_modeling", "subcategory": "Investment Advisory", "description": "Investment advisory with sovereign wealth fund consulting, asset allocation modeling, and government investment portfolio optimization.", "key_features": {"swf_advisory": True, "asset_allocation": True}, "target_users": "SWFs, pensions, endowments", "pricing_model": "Advisory fees", "stage": "public", "threat_level": "medium", "threat_score": 35.0, "feature_overlap_pct": 20.0, "quantive_advantage": "Software-driven optimization vs human advisory", "competitor_advantage": "Trusted advisor to 200+ SWFs and pensions", "market_size_billion": 3.0, "api_available": False, "open_source": False, "confidence": "high"},
    {"company_name": "Alloy Partners", "company_url": "https://alloy-partners.com", "hq_location": "London, UK", "founded_year": 2021, "employee_count": "5-10", "total_funding": "$3M", "valuation": "$15M", "product_name": "Sovereign Debt Modeler", "category": "financial_modeling", "subcategory": "Debt Modeling", "description": "Specialized sovereign debt cash flow modeling tool with scenario analysis, debt sustainability projections, and refinancing scheduling for government finance teams.", "key_features": {"cash_flow_modeling": True, "scenario_analysis": True, "sustainability": True}, "target_users": "Debt management offices", "pricing_model": "SaaS subscription", "stage": "seed_round", "threat_level": "high", "threat_score": 70.0, "feature_overlap_pct": 60.0, "quantive_advantage": "Broader platform with quantum optimization vs modeling-only tool", "competitor_advantage": "Purpose-built for DMO workflows", "market_size_billion": 0.3, "api_available": True, "open_source": False, "confidence": "medium"},

    # ── GOVTECH (35 items) ─────────────────────────────────────────
    {"company_name": "OpenGov", "company_url": "https://opengov.com", "hq_location": "San Jose, US", "founded_year": 2012, "employee_count": "500+", "total_funding": "$500M", "valuation": "$2B", "product_name": "OpenGov Budgeting", "category": "govtech", "subcategory": "Budget Software", "description": "Cloud-based government budgeting, reporting, and financial planning platform used by 1,800+ public agencies. Provides budget formulation and execution tools.", "key_features": {"budgeting": True, "financial_planning": True, "reporting": True}, "target_users": "Local and state governments", "pricing_model": "SaaS subscription", "stage": "growth", "threat_level": "medium", "threat_score": 45.0, "feature_overlap_pct": 25.0, "quantive_advantage": "Quantive focuses on sovereign debt, not local government budgets", "competitor_advantage": "Dominant US local government budgeting platform", "market_size_billion": 3.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "Sopra Banking", "company_url": "https://soprabanking.com", "hq_location": "Paris, FR", "founded_year": 1968, "employee_count": "5,000+", "total_funding": "Part of Sopra Steria", "valuation": "$10B+", "product_name": "Sopra Sovereign Banking", "category": "govtech", "subcategory": "Government Banking", "description": "Banking software for government financial institutions including central banks, sovereign wealth funds, and state-owned banks. Provides core banking and treasury systems.", "key_features": {"core_banking": True, "central_bank": True, "swf": True}, "target_users": "Central banks, state banks", "pricing_model": "Enterprise license", "stage": "public", "threat_level": "high", "threat_score": 60.0, "feature_overlap_pct": 35.0, "quantive_advantage": "Optimization-first vs banking-first approach", "competitor_advantage": "Established central bank software provider in Africa and Europe", "market_size_billion": 5.0, "api_available": True, "open_source": False, "confidence": "high"},
    {"company_name": "GovDash", "company_url": "https://govdash.com", "hq_location": "Washington, DC", "founded_year": 2020, "employee_count": "10-20", "total_funding": "$10M", "valuation": "$50M", "product_name": "GovDash Sovereign Finance", "category": "govtech", "subcategory": "Sovereign Finance", "description": "Dashboard platform for government finance ministries providing debt portfolio visualization, fiscal metrics tracking, and debt service monitoring.", "key_features": {"dashboards": True, "debt_monitoring": True, "fiscal_metrics": True}, "target_users": "Finance ministries, treasuries", "pricing_model": "SaaS subscription", "stage": "series_a", "threat_level": "high", "threat_score": 75.0, "feature_overlap_pct": 65.0, "quantive_advantage": "Quantum optimization engine vs dashboard-only reporting", "competitor_advantage": "First-mover in sovereign finance dashboards", "market_size_billion": 0.5, "api_available": True, "open_source": False, "confidence": "medium"},
    {"company_name": "Arلة", "company_url": "https://arla.tech", "hq_location": "Abuja, NG", "founded_year": 2022, "employee_count": "5-10", "total_funding": "$2M", "valuation": "$10M", "product_name": "African Debt Tracker", "category": "govtech", "subcategory": "Sovereign Finance", "description": "Open-source African sovereign debt monitoring platform tracking bilateral, multilateral, and commercial debt for 54 African nations with transparency scoring.", "key_features": {"african_focus": True, "open_data": True, "transparency": True}, "target_users": "African finance ministries, civil society", "pricing_model": "Free + premium analytics", "stage": "prototype", "threat_level": "medium", "threat_score": 50.0, "feature_overlap_pct": 45.0, "quantive_advantage": "Quantive provides optimization vs monitoring-only", "competitor_advantage": "Africa-specific debt expertise and transparency focus", "market_size_billion": 0.2, "api_available": True, "open_source": True, "confidence": "medium"},
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        existing = db.query(FintechLaunch).count()
        if existing > 0:
            print(f"[SKIP] Database already has {existing} fintech launch records")
            return

        print(f"[INFO] Seeding {len(ITEMS)} fintech launches...")
        for i, item_data in enumerate(ITEMS):
            launch = FintechLaunch(
                id=str(uuid.uuid4()),
                **item_data,
            )
            db.add(launch)

        db.commit()

        # Verify
        from sqlalchemy import func
        total = db.query(func.count(FintechLaunch.id)).scalar()
        cats = db.query(func.count(func.distinct(FintechLaunch.category))).scalar()
        print(f"\n[DONE] Seeded {total} launches across {cats} categories")

        # Breakdown
        results = db.query(FintechLaunch.category, func.count(FintechLaunch.id)).group_by(FintechLaunch.category).order_by(func.count(FintechLaunch.id).desc()).all()
        for cat, count in results:
            print(f"  {cat}: {count} items")

        # Threat breakdown
        print("\nThreat levels:")
        threats = db.query(FintechLaunch.threat_level, func.count(FintechLaunch.id)).group_by(FintechLaunch.threat_level).order_by(func.count(FintechLaunch.id).desc()).all()
        for level, count in threats:
            print(f"  {level}: {count}")

    finally:
        db.close()


if __name__ == "__main__":
    seed()
