"""Recommendation explainability — Pillar 2, Pillar 3.

Every recommendation MUST show:
  - Confidence
  - Assumptions
  - Alternative options
  - Risks
  - Data sources

NEVER show: "Recommended Action"
ALWAYS show: "Recommended Action + Why + Risks + Counterargument"

Three-layer architecture:
  Layer 1: Data (raw inputs, sources, quality)
  Layer 2: Verified Models (quantitative outputs, backtests)
  Layer 3: AI Explanation (natural language, always labeled as interpretation)

AI never becomes the source of truth. AI explains. Models decide.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Literal


@dataclass
class DataSource:
    name: str
    type: Literal["market_data", "fundamental", "government", "model_output", "user_input", "third_party"]
    quality_score: float  # 0-1
    staleness_hours: float  # how old is the data
    url: str = ""
    as_of: str = ""


@dataclass
class Risk:
    description: str
    severity: Literal["low", "medium", "high", "critical"]
    mitigation: str = ""
    probability: float = 0.5


@dataclass
class Alternative:
    description: str
    expected_return: float | None = None
    risk: float | None = None
    pros: list[str] = field(default_factory=list)
    cons: list[str] = field(default_factory=list)


@dataclass
class AssumptionRef:
    key: str
    value: Any
    source: str
    confidence: float


@dataclass
class ExplainableRecommendation:
    """A recommendation that cannot be shown without full explanation.

    This is the §68 output enriched with Pillar 2/3 explainability.
    """
    id: str
    title: str                           # "Increase AAPL allocation to 15%"
    action_type: Literal["buy", "sell", "hold", "rebalance", "hedge", "exit"]
    target: str                          # ticker, portfolio id, etc.

    # Pillar 2: confidence
    confidence: float                    # 0-1
    confidence_basis: str                # "Based on 87% backtest win rate over 5 years"
    confidence_limitations: list[str] = field(default_factory=list)

    # Pillar 2: assumptions
    assumptions: list[AssumptionRef] = field(default_factory=list)

    # Pillar 2: alternatives
    alternatives: list[Alternative] = field(default_factory=list)

    # Pillar 2: risks
    risks: list[Risk] = field(default_factory=list)

    # Pillar 3: data sources
    data_sources: list[DataSource] = field(default_factory=list)

    # Pillar 3: model layer
    model_name: str = ""
    model_version: str = ""
    backtest_period: str = ""
    backtest_metrics: dict = field(default_factory=dict)

    # Pillar 3: AI explanation layer (labeled as interpretation, not truth)
    ai_interpretation: str = ""
    ai_interpretation_disclaimer: str = "This interpretation is generated by AI and should not be treated as the sole basis for decisions."

    # Counterargument (Pillar 2)
    counterargument: str = ""

    # Metadata
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    created_by: str = "quantive-engine"
    model_version: str = ""

    def to_report(self) -> dict:
        """Full explainable report — the ONLY format recommendations should be shown in."""
        return {
            "recommendation": {
                "id": self.id,
                "title": self.title,
                "action": self.action_type,
                "target": self.target,
            },
            "confidence": {
                "score": round(self.confidence, 3),
                "basis": self.confidence_basis,
                "limitations": self.confidence_limitations,
            },
            "assumptions": [
                {"key": a.key, "value": a.value, "source": a.source, "confidence": a.confidence}
                for a in self.assumptions
            ],
            "alternatives": [
                {
                    "description": alt.description,
                    "expected_return": alt.expected_return,
                    "risk": alt.risk,
                    "pros": alt.pros,
                    "cons": alt.cons,
                }
                for alt in self.alternatives
            ],
            "risks": [
                {
                    "description": r.description,
                    "severity": r.severity,
                    "mitigation": r.mitigation,
                    "probability": r.probability,
                }
                for r in self.risks
            ],
            "data_sources": [
                {
                    "name": ds.name,
                    "type": ds.type,
                    "quality_score": round(ds.quality_score, 2),
                    "staleness_hours": round(ds.staleness_hours, 1),
                    "as_of": ds.as_of,
                }
                for ds in self.data_sources
            ],
            "model": {
                "name": self.model_name,
                "version": self.model_version,
                "backtest_period": self.backtest_period,
                "backtest_metrics": self.backtest_metrics,
            },
            "ai_interpretation": {
                "text": self.ai_interpretation,
                "disclaimer": self.ai_interpretation_disclaimer,
            },
            "counterargument": self.counterargument,
            "metadata": {
                "created_at": self.created_at.isoformat(),
                "created_by": self.created_by,
            },
        }


class ExplainabilityEngine:
    """Builds explainable recommendations. Enforces Pillar 2/3 requirements.

    Every recommendation passes through this engine before being shown to users.
    It ensures no recommendation is presented without:
    - Confidence basis
    - At least one assumption
    - At least one risk
    - At least one data source
    """

    def __init__(self, require_alternatives: bool = True, min_data_sources: int = 1) -> None:
        self.require_alternatives = require_alternatives
        self.min_data_sources = min_data_sources

    def validate(self, rec: ExplainableRecommendation) -> list[str]:
        """Validate that a recommendation meets Pillar 2/3 requirements.
        Returns list of validation errors (empty = passes)."""
        errors: list[str] = []

        if rec.confidence < 0 or rec.confidence > 1:
            errors.append("Confidence must be between 0 and 1")

        if not rec.confidence_basis:
            errors.append("Confidence basis is required (Pillar 2)")

        if not rec.assumptions:
            errors.append("At least one assumption must be documented (Pillar 2)")

        if self.require_alternatives and not rec.alternatives:
            errors.append("At least one alternative must be presented (Pillar 2)")

        if not rec.risks:
            errors.append("At least one risk must be documented (Pillar 2)")

        if len(rec.data_sources) < self.min_data_sources:
            errors.append(f"At least {self.min_data_sources} data source(s) required (Pillar 3)")

        if not rec.counterargument:
            errors.append("Counterargument is required — never present one-sided recommendations (Pillar 2)")

        if not rec.ai_interpretation:
            errors.append("AI interpretation is required, but must be labeled as interpretation (Pillar 3)")

        return errors

    def build(
        self,
        *,
        rec_id: str,
        title: str,
        action_type: Literal["buy", "sell", "hold", "rebalance", "hedge", "exit"],
        target: str,
        confidence: float,
        confidence_basis: str,
        confidence_limitations: list[str] | None = None,
        assumptions: list[AssumptionRef] | None = None,
        alternatives: list[Alternative] | None = None,
        risks: list[Risk] | None = None,
        data_sources: list[DataSource] | None = None,
        model_name: str = "",
        model_version: str = "",
        backtest_period: str = "",
        backtest_metrics: dict | None = None,
        ai_interpretation: str = "",
        counterargument: str = "",
        created_by: str = "quantive-engine",
    ) -> ExplainableRecommendation:
        """Build an explainable recommendation. Validates before returning."""
        rec = ExplainableRecommendation(
            id=rec_id,
            title=title,
            action_type=action_type,
            target=target,
            confidence=confidence,
            confidence_basis=confidence_basis,
            confidence_limitations=confidence_limitations or [],
            assumptions=assumptions or [],
            alternatives=alternatives or [],
            risks=risks or [],
            data_sources=data_sources or [],
            model_name=model_name,
            model_version=model_version,
            backtest_period=backtest_period,
            backtest_metrics=backtest_metrics or {},
            ai_interpretation=ai_interpretation,
            counterargument=counterargument,
            created_by=created_by,
        )

        errors = self.validate(rec)
        if errors:
            raise ValueError(f"Recommendation fails Pillar 2/3 validation: {'; '.join(errors)}")

        return rec

    def from_quantive_output(
        self,
        *,
        ticker: str,
        weight: float,
        prev_weight: float,
        expected_return: float,
        risk: float,
        confidence: float,
        model_name: str = "quantive-ensemble",
        assumptions: list[AssumptionRef] | None = None,
        data_sources: list[DataSource] | None = None,
    ) -> ExplainableRecommendation:
        """Auto-build from Quantive engine output with sensible defaults.

        This is the main integration point: engine outputs → explainable recommendation.
        """
        action = "hold"
        if weight > prev_weight + 0.01:
            action = "buy"
        elif weight < prev_weight - 0.01:
            action = "sell"
        elif abs(weight - prev_weight) < 0.005:
            action = "hold"
        else:
            action = "rebalance"

        delta = weight - prev_weight

        return self.build(
            rec_id=f"rec-{ticker}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
            title=f"{'Increase' if delta > 0 else 'Decrease'} {ticker} allocation to {weight:.1%}",
            action_type=action,
            target=ticker,
            confidence=confidence,
            confidence_basis=f"Model confidence {confidence:.0%} based on ensemble prediction consistency",
            confidence_limitations=[
                "Confidence based on historical patterns; does not predict black swan events",
                "Model trained on past data; regime changes may reduce accuracy",
            ],
            assumptions=assumptions or [
                AssumptionRef(key="risk_free_rate", value=0.02, source="US Treasury 10Y", confidence=0.9),
                AssumptionRef(key="market_regime", value="normal", source="regime_engine", confidence=0.7),
            ],
            alternatives=[
                Alternative(
                    description=f"Maintain current {prev_weight:.1%} allocation",
                    pros=["Lower transaction costs", "No change in risk profile"],
                    cons=["Misses potential upside" if delta > 0 else "Does not reduce downside exposure"],
                ),
                Alternative(
                    description=f"{'Reduce' if delta > 0 else 'Increase'} to {max(0, weight - delta):.1%}",
                    expected_return=expected_return * 0.5,
                    risk=risk * 0.8,
                    pros=["More conservative", "Lower drawdown risk"],
                    cons=["Lower expected return"],
                ),
            ],
            risks=[
                Risk(
                    description=f"Model error: {ticker} expected return {expected_return:.1%} may not materialize",
                    severity="medium" if confidence > 0.7 else "high",
                    mitigation="Position sized to limit max loss",
                    probability=1 - confidence,
                ),
                Risk(
                    description=f"Concentration: {ticker} at {weight:.1%} of portfolio",
                    severity="high" if weight > 0.20 else "low",
                    mitigation="Capped at 25% max position",
                    probability=0.1,
                ),
            ],
            data_sources=data_sources or [
                DataSource(name="Yahoo Finance", type="market_data", quality_score=0.85, staleness_hours=1),
                DataSource(name="Quantive Ensemble Model", type="model_output", quality_score=confidence, staleness_hours=0),
            ],
            model_name=model_name,
            model_version="0.1.0",
            ai_interpretation=(
                f"The model recommends {'increasing' if delta > 0 else 'decreasing'} {ticker} "
                f"from {prev_weight:.1%} to {weight:.1%}. "
                f"Expected return: {expected_return:.1%}, Risk: {risk:.1%}. "
                f"This is an AI interpretation of model outputs — not a guarantee."
            ),
            counterargument=(
                f"Counterargument: Maintaining the current {prev_weight:.1%} allocation avoids "
                f"transaction costs and reduces the risk of model error. "
                f"The expected return of {expected_return:.1%} is based on historical patterns "
                f"that may not repeat."
            ),
        )
