[package]
name = "omnichain-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
omnichain-types = { path = "../types" }
serde.workspace = true
serde_json.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
hex.workspace = true
sha3.workspace = true
reqwest = { version = "0.12", features = ["json"], optional = true }

[features]
default = []
rpc = ["dep:reqwest"]
