"""Advanced scenario models: regime-switching and historical simulation.

Regime-switching models capture the reality that financial markets
transition between distinct states (expansion, recession, crisis) with
different parameter characteristics.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

import numpy as np

from quantive.data.synthetic import FX_VOLATILITY
from quantive.models.optimization import EconomicScenario


@dataclass
class Regime:
    """A market regime with specific parameter characteristics."""
    name: str
    interest_rate_shock_mean: float = 0.0
    interest_rate_shock_std: float = 0.015
    inflation_shock_mean: float = 0.0
    inflation_shock_std: float = 0.01
    liquidity_factor_mean: float = 0.85
    liquidity_factor_std: float = 0.1
    fx_shock_mean: float = 0.0
    probability: float = 0.25


# Predefined regimes
EXPANSION = Regime(
    name="Expansion",
    interest_rate_shock_mean=-0.005,
    interest_rate_shock_std=0.010,
    inflation_shock_mean=-0.003,
    inflation_shock_std=0.008,
    liquidity_factor_mean=0.95,
    liquidity_factor_std=0.05,
    fx_shock_mean=-0.01,
    probability=0.35,
)

NORMAL = Regime(
    name="Normal",
    interest_rate_shock_mean=0.0,
    interest_rate_shock_std=0.015,
    inflation_shock_mean=0.0,
    inflation_shock_std=0.010,
    liquidity_factor_mean=0.90,
    liquidity_factor_std=0.08,
    fx_shock_mean=0.0,
    probability=0.30,
)

STRESS = Regime(
    name="Stress",
    interest_rate_shock_mean=0.015,
    interest_rate_shock_std=0.020,
    inflation_shock_mean=0.010,
    inflation_shock_std=0.015,
    liquidity_factor_mean=0.65,
    liquidity_factor_std=0.15,
    fx_shock_mean=0.05,
    probability=0.20,
)

CRISIS = Regime(
    name="Crisis",
    interest_rate_shock_mean=0.030,
    interest_rate_shock_std=0.030,
    inflation_shock_mean=0.020,
    inflation_shock_std=0.020,
    liquidity_factor_mean=0.40,
    liquidity_factor_std=0.20,
    fx_shock_mean=0.10,
    probability=0.15,
)

DEFAULT_REGIMES = [EXPANSION, NORMAL, STRESS, CRISIS]


class RegimeSwitchingEngine:
    """Generate scenarios using a regime-switching model.

    Each scenario is generated by first sampling a regime, then drawing
    shocks from that regime's parameter distribution. The regime
    transition probabilities can be estimated from historical data or
    set manually.
    """

    def __init__(
        self,
        regimes: Optional[List[Regime]] = None,
        seed: int = 42,
    ):
        self.regimes = regimes or DEFAULT_REGIMES
        self._rng = np.random.default_rng(seed)
        # Normalize regime probabilities
        total_prob = sum(r.probability for r in self.regimes)
        self._regime_probs = np.array([r.probability / total_prob for r in self.regimes])

    def generate(
        self,
        count: int,
        currencies: Optional[List[str]] = None,
    ) -> List[EconomicScenario]:
        """Generate regime-switching scenarios."""
        if count <= 0:
            return []

        currencies = currencies or sorted(FX_VOLATILITY.keys())
        scenarios: List[EconomicScenario] = []

        for i in range(count):
            # Sample a regime
            regime_idx = int(self._rng.choice(len(self.regimes), p=self._regime_probs))
            regime = self.regimes[regime_idx]

            # Draw shocks from regime parameters
            ir_shock = float(self._rng.normal(
                regime.interest_rate_shock_mean,
                regime.interest_rate_shock_std,
            ))
            inf_shock = float(self._rng.normal(
                regime.inflation_shock_mean,
                regime.inflation_shock_std,
            ))
            liq = float(np.clip(
                self._rng.normal(regime.liquidity_factor_mean, regime.liquidity_factor_std),
                0.10, 1.0,
            ))

            # FX shocks
            fx: Dict[str, float] = {}
            for c in currencies:
                if c == "USD":
                    fx[c] = 1.0
                else:
                    vol = FX_VOLATILITY.get(c, 0.10)
                    log_shock = float(self._rng.normal(regime.fx_shock_mean, vol))
                    fx[c] = float(np.exp(log_shock))

            scenarios.append(EconomicScenario(
                id=f"regime-{regime.name.lower()}-{i:05d}",
                name=f"{regime.name} #{i+1}",
                probability=1.0 / count,
                interest_rate_shock=round(ir_shock, 6),
                inflation_shock=round(inf_shock, 6),
                fx_shocks=fx,
                liquidity_conditions=round(liq, 4),
            ))

        return scenarios


class HistoricalSimulationEngine:
    """Generate scenarios using historical simulation.

    Takes a matrix of historical changes and applies them as shocks
    to the current state. This is a non-parametric approach that
    preserves the empirical dependency structure of the data.
    """

    def __init__(self, seed: int = 42):
        self._rng = np.random.default_rng(seed)

    def generate(
        self,
        count: int,
        historical_rates: Optional[np.ndarray] = None,
        historical_fx: Optional[np.ndarray] = None,
        currencies: Optional[List[str]] = None,
    ) -> List[EconomicScenario]:
        """Generate historical simulation scenarios.

        If no historical data is provided, generates synthetic "historical"
        paths using bootstrap resampling.
        """
        if count <= 0:
            return []

        currencies = currencies or sorted(FX_VOLATILITY.keys())

        if historical_rates is None:
            # Generate synthetic "historical" rate paths
            n_history = 252  # ~1 year of daily observations
            historical_rates = self._rng.normal(0.0, 0.015, size=(n_history,))

        if historical_fx is None:
            n_history = len(historical_rates)
            historical_fx = {}
            for c in currencies:
                if c == "USD":
                    continue
                vol = FX_VOLATILITY.get(c, 0.10)
                historical_fx[c] = self._rng.normal(0.0, vol, size=(n_history,))

        n_history = len(historical_rates)
        scenarios: List[EconomicScenario] = []

        for i in range(count):
            # Bootstrap sample a historical observation
            idx = int(self._rng.integers(0, n_history))

            ir_shock = float(historical_rates[idx])
            inf_shock = ir_shock * 0.5 + float(self._rng.normal(0, 0.005))  # correlated
            liq = float(np.clip(1.0 - 0.3 * max(0.0, ir_shock / 0.015), 0.20, 1.0))

            fx: Dict[str, float] = {}
            for c in currencies:
                if c == "USD":
                    fx[c] = 1.0
                elif c in historical_fx:
                    log_move = float(historical_fx[c][idx])
                    fx[c] = float(np.exp(log_move))
                else:
                    fx[c] = 1.0

            scenarios.append(EconomicScenario(
                id=f"historical-{i:05d}",
                name=f"Historical Sim #{i+1}",
                probability=1.0 / count,
                interest_rate_shock=round(ir_shock, 6),
                inflation_shock=round(inf_shock, 6),
                fx_shocks=fx,
                liquidity_conditions=round(liq, 4),
            ))

        return scenarios
